import {
  StudentProfile,
  MyTeamResponse,
  ProjectResponse,
  MyFilesResponse,
  SubmissionChecklist,
  MySubmissionResponse,
  AdvisorDashboardResponse,
  AdvisorTeamSummary,
  AdvisorStudent,
  SubmissionCompleteness,
  TeamEvaluationResponse,
  StudentEvaluationResponse,
  DeadlineResponse,
  NotificationResponse,
  LoginResponse,
} from "@/types";

export const mockStudentUser: LoginResponse = {
  access_token: "demo_jwt_student_token_siet_autonomous",
  token_type: "bearer",
  user: {
    id: "student-uuid-demo-001",
    roll_number: "23CS001",
    full_name: "Rahul Sharma",
    email: "rahul.23cs@siet.ac.in",
    role: "student",
    team_id: "team-uuid-alpha-001",
  },
};

export const mockAdvisorUser: LoginResponse = {
  access_token: "demo_jwt_advisor_token_siet_autonomous",
  token_type: "bearer",
  user: {
    id: "advisor-uuid-demo-001",
    roll_number: null,
    full_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
    email: "senthilkumar.cse@siet.ac.in",
    role: "advisor",
    team_id: null,
  },
};

export const mockStudentProfile: StudentProfile = {
  id: "student-uuid-demo-001",
  roll_number: "23CS001",
  full_name: "Rahul Sharma",
  email: "rahul.23cs@siet.ac.in",
  role: "student",
  team_id: "team-uuid-alpha-001",
};

export const mockTeam: MyTeamResponse = {
  team_id: "team-uuid-alpha-001",
  name: "Team Alpha (CSE-A)",
  project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
  batch: "2023-2027",
  section: "A",
  team_leader: {
    id: "student-uuid-demo-001",
    roll_number: "23CS001",
    full_name: "Rahul Sharma",
    is_team_leader: true,
  },
  members: [
    {
      id: "student-uuid-demo-001",
      roll_number: "23CS001",
      full_name: "Rahul Sharma",
      is_team_leader: true,
      email: "rahul.23cs@siet.ac.in",
    },
    {
      id: "student-uuid-demo-002",
      roll_number: "23CS014",
      full_name: "Priya Dharshini",
      is_team_leader: false,
      email: "priya.23cs@siet.ac.in",
    },
    {
      id: "student-uuid-demo-003",
      roll_number: "23CS028",
      full_name: "Karthik Raja",
      is_team_leader: false,
      email: "karthik.23cs@siet.ac.in",
    },
    {
      id: "student-uuid-demo-004",
      roll_number: "23CS042",
      full_name: "Ananya Iyer",
      is_team_leader: false,
      email: "ananya.23cs@siet.ac.in",
    },
  ],
  advisor: {
    id: "advisor-uuid-demo-001",
    full_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
    email: "senthilkumar.cse@siet.ac.in",
  },
};

export const mockProject: ProjectResponse = {
  id: "proj-uuid-demo-001",
  team_id: "team-uuid-alpha-001",
  title: "AI-Powered Smart Attendance & Campus Surveillance System",
  domain: "Artificial Intelligence & Edge Computing",
  problem_statement:
    "Manual attendance logging in large autonomous universities causes an average 12-minute delay per lecture block and suffers from proxy entries. Traditional biometric scanners also cause physical bottlenecks during morning peak arrivals.",
  description:
    "An edge-computing computer vision platform that performs multi-camera facial recognition and tracking across university entrance portals and lecture halls, synchronizing verified student arrivals directly to the autonomous ERP in real-time.",
  proposed_solution:
    "Deploying lightweight YOLOv11 + FaceNet embedding extraction models optimized via ONNX Runtime on edge Jetson nodes. Cryptographic HMAC timestamps prevent spoofing, and automated alerts report unauthorized campus entries to administrative security.",
  technologies_used:
    "Python, FastAPI, PyTorch, YOLOv11, Next.js, PostgreSQL, Docker, Redis",
  github_url: "https://github.com/siet-autonomous/ai-smart-attendance",
  live_demo_url: "https://attendance.siet-demo.ac.in",
};

export const mockFiles: MyFilesResponse = {
  count: 3,
  files: [
    {
      id: "file-uuid-001",
      project_id: "proj-uuid-demo-001",
      team_id: "team-uuid-alpha-001",
      category: "ABSTRACT",
      original_filename: "SIET_PRC_Abstract_TeamAlpha_v2.pdf",
      storage_path: "teams/team-alpha/abstract.pdf",
      mime_type: "application/pdf",
      file_size: 1450230,
      created_at: "2026-08-28T10:30:00Z",
      updated_at: "2026-08-28T10:30:00Z",
    },
    {
      id: "file-uuid-002",
      project_id: "proj-uuid-demo-001",
      team_id: "team-uuid-alpha-001",
      category: "REPORT",
      original_filename: "TeamAlpha_Project_Report_Final_IEEE.pdf",
      storage_path: "teams/team-alpha/report.pdf",
      mime_type: "application/pdf",
      file_size: 4892300,
      created_at: "2026-09-01T14:15:00Z",
      updated_at: "2026-09-01T14:15:00Z",
    },
    {
      id: "file-uuid-003",
      project_id: "proj-uuid-demo-001",
      team_id: "team-uuid-alpha-001",
      category: "PPT",
      original_filename: "TeamAlpha_VivaVoce_Presentation_Deck.pptx",
      storage_path: "teams/team-alpha/presentation.pptx",
      mime_type: "application/vnd.ms-powerpoint",
      file_size: 6120400,
      created_at: "2026-09-02T09:45:00Z",
      updated_at: "2026-09-02T09:45:00Z",
    },
  ],
};

export const mockChecklist: SubmissionChecklist = {
  abstract: { completed: true, label: "Abstract Document (PDF)" },
  report: { completed: true, label: "Comprehensive Project Report (PDF)" },
  ppt: { completed: true, label: "Presentation Slide Deck (PPT)" },
  images: { completed: true, label: "Project Architecture & Screenshots" },
  github: { completed: true, label: "GitHub Repository VCS Link" },
  live_demo: { completed: true, label: "Live Deployment / Video URL" },
  completed_count: 6,
  total_count: 6,
  all_completed: true,
};

export const mockSubmission: MySubmissionResponse = {
  submission_id: "sub-uuid-demo-001",
  status: "SUBMITTED",
  submitted_at: "2026-09-02T16:20:00Z",
  checklist: mockChecklist,
  files: mockFiles.files,
  project: mockProject,
};

export const mockAdvisorDashboard: AdvisorDashboardResponse = {
  advisor_id: "advisor-uuid-demo-001",
  total_teams: 5,
  total_students: 20,
  submitted_count: 4,
  pending_submissions: 1,
  evaluated_count: 2,
  pending_evaluations: 3,
  recent_submissions: [
    {
      submission_id: "sub-uuid-demo-001",
      team_name: "Team Alpha (CSE-A)",
      project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
      submitted_at: "2026-09-02T16:20:00Z",
      status: "SUBMITTED",
      guide: {
        id: "faculty-subramanian",
        name: "Dr. Subramanian",
        full_name: "Dr. Subramanian",
        designation: "Professor",
        department: "CSE",
        email: "subramanian.cse@siet.ac.in",
      },
    },
    {
      submission_id: "sub-uuid-demo-002",
      team_name: "Team Beta (CSE-A)",
      project_title: "Autonomous Drone Delivery for Hospital Supplies",
      submitted_at: "2026-09-01T11:45:00Z",
      status: "APPROVED",
      guide: {
        id: "faculty-arunkumar",
        name: "Dr. Arun Kumar",
        full_name: "Dr. Arun Kumar",
        designation: "Assistant Professor",
        department: "CSE",
        email: "arunkumar.cse@siet.ac.in",
      },
    },
    {
      submission_id: "sub-uuid-demo-003",
      team_name: "Team Delta (CSE-B)",
      project_title: "Decentralized Credential Verification using Polygon",
      submitted_at: "2026-08-30T14:10:00Z",
      status: "EVALUATED",
      guide: {
        id: "faculty-rajesh",
        name: "Dr. K. Rajesh",
        full_name: "Dr. K. Rajesh",
        designation: "Associate Professor",
        department: "CSE",
        email: "rajesh.cse@siet.ac.in",
      },
    },
  ],
  recent_activities: [
    {
      id: "act-1",
      title: "Team Alpha uploaded final presentation slides",
      timestamp: "2 hours ago",
      type: "FILE_UPLOAD",
    },
    {
      id: "act-2",
      title: "Team Beta was marked APPROVED for Final Viva Voce",
      timestamp: "Yesterday",
      type: "REVIEW_APPROVED",
    },
    {
      id: "act-3",
      title: "Reminder broadcasted for Phase II deadline",
      timestamp: "2 days ago",
      type: "DEADLINE_NOTICE",
    },
  ],
};

export const mockAdvisorTeams: AdvisorTeamSummary[] = [
  {
    team_id: "team-uuid-alpha-001",
    name: "Team Alpha",
    project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
    batch: "2023-2027",
    section: "A",
    department: "Computer Science & Engineering",
    guide: {
      id: "faculty-subramanian",
      name: "Dr. Subramanian",
      full_name: "Dr. Subramanian",
      designation: "Professor",
      department: "CSE",
      email: "subramanian.cse@siet.ac.in",
    },
    members: [
      { id: "student-uuid-demo-001", student_id: "student-uuid-demo-001", roll_number: "23CS001", full_name: "Rahul Sharma", email: "rahul.23cs@siet.ac.in", is_team_leader: true, is_leader: true },
      { id: "student-uuid-demo-002", student_id: "student-uuid-demo-002", roll_number: "23CS014", full_name: "Priya Dharshini", email: "priya.23cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "student-uuid-demo-003", student_id: "student-uuid-demo-003", roll_number: "23CS028", full_name: "Karthik Raja", email: "karthik.23cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "student-uuid-demo-004", student_id: "student-uuid-demo-004", roll_number: "23CS042", full_name: "Ananya Iyer", email: "ananya.23cs@siet.ac.in", is_team_leader: false, is_leader: false },
    ],
    members_names: ["Rahul Sharma (23CS001)", "Priya Dharshini (23CS014)", "Karthik Raja (23CS028)", "Ananya Iyer (23CS042)"],
    current_phase: "Phase II / Final Viva",
    submitted_at: "2026-09-02T16:20:00Z",
    submission_status: "SUBMITTED",
    evaluation_status: "EVALUATED",
    evaluation: {
      id: "eval-uuid-001",
      team_score: 92,
      team_remarks: "Exceptional architecture, robust code repository, and thorough literature review. Meets all autonomous college guidelines.",
      status: "EVALUATED",
      created_at: "2026-09-02T18:30:00Z",
      strengths: "Comprehensive architecture, clean modular code structure, and strong literature survey.",
      areas_for_improvement: "Expand automated test coverage and include benchmark latency graphs in the final appendix.",
      recommendation_status: "APPROVED",
      criteria_scores: {
        project: 19,
        technical: 18.5,
        presentation: 18,
        documentation: 18.5,
        contribution: 18,
      },
    },
    member_count: 4,
    leader: {
      id: "student-uuid-demo-001",
      roll_number: "23CS001",
      full_name: "Rahul Sharma",
      email: "rahul.23cs@siet.ac.in",
      is_team_leader: true,
    },
  },
  {
    team_id: "team-uuid-beta-002",
    name: "Team Beta",
    project_title: "Autonomous Drone Delivery for Hospital Supplies",
    batch: "2023-2027",
    section: "A",
    department: "Computer Science & Engineering",
    guide: {
      id: "faculty-arunkumar",
      name: "Dr. Arun Kumar",
      full_name: "Dr. Arun Kumar",
      designation: "Assistant Professor",
      department: "CSE",
      email: "arunkumar.cse@siet.ac.in",
    },
    members: [
      { id: "student-uuid-demo-005", student_id: "student-uuid-demo-005", roll_number: "23CS018", full_name: "Vigneshwaran K", email: "vignesh.23cs@siet.ac.in", is_team_leader: true, is_leader: true },
      { id: "student-uuid-demo-006", student_id: "student-uuid-demo-006", roll_number: "23CS022", full_name: "Divya M", email: "divya.23cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "student-uuid-demo-007", student_id: "student-uuid-demo-007", roll_number: "23CS033", full_name: "Siddharth P", email: "siddharth.23cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "student-uuid-demo-008", student_id: "student-uuid-demo-008", roll_number: "23CS045", full_name: "Nandhini S", email: "nandhini.23cs@siet.ac.in", is_team_leader: false, is_leader: false },
    ],
    members_names: ["Vigneshwaran K (23CS018)", "Divya M (23CS022)", "Siddharth P (23CS033)", "Nandhini S (23CS045)"],
    current_phase: "Phase II / Final Viva",
    submitted_at: "2026-09-01T11:45:00Z",
    submission_status: "APPROVED",
    evaluation_status: "EVALUATED",
    evaluation: {
      id: "eval-uuid-002",
      team_score: 95,
      team_remarks: "Outstanding hardware implementation and real-time telemetry testing. Excellent viva defense.",
      status: "APPROVED",
      created_at: "2026-09-01T14:10:00Z",
      strengths: "Real hardware flight controller integration, fail-safe GPS recovery.",
      areas_for_improvement: "Document battery life benchmarks under loaded conditions.",
      recommendation_status: "EXCELLENT",
      criteria_scores: {
        project: 19.5,
        technical: 19,
        presentation: 19,
        documentation: 18.5,
        contribution: 19,
      },
    },
    member_count: 4,
    leader: {
      id: "student-uuid-demo-005",
      roll_number: "23CS018",
      full_name: "Vigneshwaran K",
      email: "vignesh.23cs@siet.ac.in",
      is_team_leader: true,
    },
  },
  {
    team_id: "team-uuid-gamma-003",
    name: "Team Gamma",
    project_title: "IoT Sensor Fusion for Precision Agriculture & Irrigation",
    batch: "2023-2027",
    section: "A",
    department: "Computer Science & Engineering",
    guide: {
      id: "faculty-meenadevi",
      name: "Dr. Meena Devi",
      full_name: "Dr. Meena Devi",
      designation: "Professor",
      department: "CSE",
      email: "meenadevi.cse@siet.ac.in",
    },
    members: [
      { id: "student-uuid-demo-009", student_id: "student-uuid-demo-009", roll_number: "23CS035", full_name: "Meera Krishnan", email: "meera.23cs@siet.ac.in", is_team_leader: true, is_leader: true },
      { id: "student-uuid-demo-010", student_id: "student-uuid-demo-010", roll_number: "23CS040", full_name: "Gokul Nath", email: "gokul.23cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "student-uuid-demo-011", student_id: "student-uuid-demo-011", roll_number: "23CS052", full_name: "Harini R", email: "harini.23cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "student-uuid-demo-012", student_id: "student-uuid-demo-012", roll_number: "23CS061", full_name: "Dinesh K", email: "dinesh.23cs@siet.ac.in", is_team_leader: false, is_leader: false },
    ],
    members_names: ["Meera Krishnan (23CS035)", "Gokul Nath (23CS040)", "Harini R (23CS052)", "Dinesh K (23CS061)"],
    current_phase: "Phase I Review",
    submitted_at: undefined,
    submission_status: "NOT_SUBMITTED",
    evaluation_status: "PENDING",
    member_count: 4,
    leader: {
      id: "student-uuid-demo-009",
      roll_number: "23CS035",
      full_name: "Meera Krishnan",
      email: "meera.23cs@siet.ac.in",
      is_team_leader: true,
    },
  },
  {
    team_id: "team-uuid-delta-004",
    name: "Team Delta",
    project_title: "Decentralized Credential Verification using Polygon",
    batch: "2023-2027",
    section: "B",
    department: "Computer Science & Engineering",
    guide: {
      id: "faculty-rajesh",
      name: "Dr. K. Rajesh",
      full_name: "Dr. K. Rajesh",
      designation: "Associate Professor",
      department: "CSE",
      email: "rajesh.cse@siet.ac.in",
    },
    members: [
      { id: "student-uuid-demo-013", student_id: "student-uuid-demo-013", roll_number: "23CS050", full_name: "Arjun Reddy", email: "arjun.23cs@siet.ac.in", is_team_leader: true, is_leader: true },
      { id: "student-uuid-demo-014", student_id: "student-uuid-demo-014", roll_number: "23CS058", full_name: "Pooja S", email: "pooja.23cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "student-uuid-demo-015", student_id: "student-uuid-demo-015", roll_number: "23CS065", full_name: "Naveen Kumar", email: "naveen.23cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "student-uuid-demo-016", student_id: "student-uuid-demo-016", roll_number: "23CS070", full_name: "Swetha M", email: "swetha.23cs@siet.ac.in", is_team_leader: false, is_leader: false },
    ],
    members_names: ["Arjun Reddy (23CS050)", "Pooja S (23CS058)", "Naveen Kumar (23CS065)", "Swetha M (23CS070)"],
    current_phase: "Phase II / Final Viva",
    submitted_at: "2026-08-30T14:10:00Z",
    submission_status: "SUBMITTED",
    evaluation_status: "EVALUATED",
    evaluation: {
      id: "eval-uuid-003",
      team_score: 88,
      team_remarks: "Smart contracts deployed on testnet, verification time under 2 seconds.",
      status: "EVALUATED",
      created_at: "2026-08-31T16:00:00Z",
      strengths: "Decentralized architecture, gas optimization.",
      areas_for_improvement: "Add formal verification report for smart contract security.",
      recommendation_status: "APPROVED",
      criteria_scores: {
        project: 18,
        technical: 18,
        presentation: 17,
        documentation: 17.5,
        contribution: 17.5,
      },
    },
    member_count: 4,
    leader: {
      id: "student-uuid-demo-013",
      roll_number: "23CS050",
      full_name: "Arjun Reddy",
      email: "arjun.23cs@siet.ac.in",
      is_team_leader: true,
    },
  },
  {
    team_id: "team-uuid-epsilon-005",
    name: "Team Epsilon",
    project_title: "Edge Vision Defect Detection for Automotive Assembly Lines",
    batch: "2023-2027",
    section: "B",
    department: "Computer Science & Engineering",
    guide: {
      id: "faculty-kavitha",
      name: "Dr. S. Kavitha",
      full_name: "Dr. S. Kavitha",
      designation: "Associate Professor",
      department: "CSE",
      email: "kavitha.cse@siet.ac.in",
    },
    members: [
      { id: "student-uuid-demo-017", student_id: "student-uuid-demo-017", roll_number: "23CS072", full_name: "Sneha Nair", email: "sneha.23cs@siet.ac.in", is_team_leader: true, is_leader: true },
      { id: "student-uuid-demo-018", student_id: "student-uuid-demo-018", roll_number: "23CS079", full_name: "Aravind B", email: "aravind.23cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "student-uuid-demo-019", student_id: "student-uuid-demo-019", roll_number: "23CS085", full_name: "Keerthana V", email: "keerthana.23cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "student-uuid-demo-020", student_id: "student-uuid-demo-020", roll_number: "23CS091", full_name: "Manoj P", email: "manoj.23cs@siet.ac.in", is_team_leader: false, is_leader: false },
    ],
    members_names: ["Sneha Nair (23CS072)", "Aravind B (23CS079)", "Keerthana V (23CS085)", "Manoj P (23CS091)"],
    current_phase: "Phase II / Final Viva",
    submitted_at: "2026-09-02T09:15:00Z",
    submission_status: "SUBMITTED",
    evaluation_status: "PENDING",
    member_count: 4,
    leader: {
      id: "student-uuid-demo-017",
      roll_number: "23CS072",
      full_name: "Sneha Nair",
      email: "sneha.23cs@siet.ac.in",
      is_team_leader: true,
    },
  },
];

export const mockAdvisorStudents: AdvisorStudent[] = [
  {
    id: "student-uuid-demo-001",
    roll_number: "23CS001",
    full_name: "Rahul Sharma",
    email: "rahul.23cs@siet.ac.in",
    team_name: "Team Alpha (CSE-A)",
    team_id: "team-uuid-alpha-001",
    project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
    evaluation_status: "EVALUATED",
    total_marks: 93,
    guide: {
      name: "Dr. Subramanian",
      designation: "Professor",
      department: "CSE",
    },
  },
  {
    id: "student-uuid-demo-002",
    roll_number: "23CS014",
    full_name: "Priya Dharshini",
    email: "priya.23cs@siet.ac.in",
    team_name: "Team Alpha (CSE-A)",
    team_id: "team-uuid-alpha-001",
    project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
    evaluation_status: "EVALUATED",
    total_marks: 91,
    guide: {
      name: "Dr. Subramanian",
      designation: "Professor",
      department: "CSE",
    },
  },
  {
    id: "student-uuid-demo-003",
    roll_number: "23CS028",
    full_name: "Karthik Raja",
    email: "karthik.23cs@siet.ac.in",
    team_name: "Team Alpha (CSE-A)",
    team_id: "team-uuid-alpha-001",
    project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
    evaluation_status: "EVALUATED",
    total_marks: 88,
    guide: {
      name: "Dr. Subramanian",
      designation: "Professor",
      department: "CSE",
    },
  },
  {
    id: "student-uuid-demo-004",
    roll_number: "23CS042",
    full_name: "Ananya Iyer",
    email: "ananya.23cs@siet.ac.in",
    team_name: "Team Alpha (CSE-A)",
    team_id: "team-uuid-alpha-001",
    project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
    evaluation_status: "EVALUATED",
    total_marks: 94,
    guide: {
      name: "Dr. Subramanian",
      designation: "Professor",
      department: "CSE",
    },
  },
  {
    id: "student-uuid-demo-005",
    roll_number: "23CS018",
    full_name: "Vigneshwaran K",
    email: "vignesh.23cs@siet.ac.in",
    team_name: "Team Beta (CSE-A)",
    team_id: "team-uuid-beta-002",
    project_title: "Autonomous Drone Delivery for Hospital Supplies",
    evaluation_status: "EVALUATED",
    total_marks: 95,
    guide: {
      name: "Dr. Arun Kumar",
      designation: "Assistant Professor",
      department: "CSE",
    },
  },
];

export const mockCompleteness: SubmissionCompleteness = {
  submission_id: "sub-uuid-demo-001",
  team_id: "team-uuid-alpha-001",
  all_completed: true,
  completed_count: 6,
  total_count: 6,
  completion_status: "COMPLETE",
  items: [
    { category: "ABSTRACT", label: "Abstract Document", completed: true },
    { category: "REPORT", label: "Project Report", completed: true },
    { category: "PPT", label: "Presentation Slides", completed: true },
    { category: "IMAGE", label: "Project Images & Diagrams", completed: true },
    { category: "GITHUB", label: "GitHub Repository URL", completed: true },
    { category: "LIVE_DEMO", label: "Live Deployment URL", completed: true },
  ],
};

export const mockTeamEvaluation: TeamEvaluationResponse = {
  id: "eval-uuid-001",
  evaluation_id: "eval-uuid-001",
  team_id: "team-uuid-alpha-001",
  team_score: 92.5,
  team_remarks: "Exceptional architecture, robust code repository, and thorough literature review.",
  status: "EVALUATED",
};

export const mockDeadlines: DeadlineResponse[] = [
  {
    id: "deadline-1",
    team_id: "team-uuid-alpha-001",
    title: "Phase II Comprehensive Report & Slides Cutoff",
    description: "Submit complete IEEE formatted report PDF, presentation deck, and verified GitHub link.",
    deadline_at: "2026-09-15T23:59:59Z",
    created_at: "2026-08-20T10:00:00Z",
  },
  {
    id: "deadline-2",
    team_id: "team-uuid-beta-002",
    title: "Final Viva Voce Committee Presentation",
    description: "Present live working hardware/software prototype before internal examination board.",
    deadline_at: "2026-09-22T14:30:00Z",
    created_at: "2026-08-25T11:00:00Z",
  },
];

export const mockNotifications: NotificationResponse[] = [
  {
    id: "notif-1",
    advisor_id: "advisor-uuid-demo-001",
    title: "Team Alpha Submitted Project Dossier",
    message: "Team Alpha has frozen all 6 checklist deliverables for final PRC evaluation.",
    is_read: false,
    created_at: "2026-09-02T16:20:00Z",
  },
  {
    id: "notif-2",
    advisor_id: "advisor-uuid-demo-001",
    title: "Team Beta Revision Approved",
    message: "Report documentation for Team Beta has been marked Approved.",
    is_read: true,
    created_at: "2026-09-01T12:00:00Z",
  },
  {
    id: "notif-3",
    advisor_id: "advisor-uuid-demo-001",
    title: "Reminder: Viva Voce Scoring Schedule",
    message: "Phase II marks must be committed to the Controller of Examinations by Sept 25.",
    is_read: true,
    created_at: "2026-08-30T09:00:00Z",
  },
];

// ========== HOD PORTAL MOCK DATA ==========

import type {
  HodDashboardStats,
  HodFacultyMember,
  HodApprovalRecord,
} from "@/types";

export const mockHodUser: LoginResponse = {
  access_token: "demo_jwt_hod_token_siet_autonomous",
  token_type: "bearer",
  user: {
    id: "hod-uuid-demo-001",
    roll_number: null,
    full_name: "Dr. R. Venkatesh, M.E., Ph.D.",
    email: "venkatesh.hod.cse@siet.ac.in",
    role: "hod",
    team_id: null,
  },
};

export const mockHodDashboardStats: HodDashboardStats = {
  total_teams: 14,
  total_students: 56,
  total_faculty: 5,
  total_projects: 14,
  evaluations_completed: 8,
  evaluations_pending: 6,
  approvals_pending: 3,
  submissions_received: 11,
  batches: ["2023-2027", "2024-2028", "2025-2029"],
};

export const mockHodFaculty: HodFacultyMember[] = [
  {
    id: "faculty-subramanian",
    name: "Dr. Subramanian",
    designation: "Professor",
    department: "CSE",
    email: "subramanian.cse@siet.ac.in",
    teams_assigned: 3,
    specialization: "Artificial Intelligence & Machine Learning",
  },
  {
    id: "faculty-arunkumar",
    name: "Dr. Arun Kumar",
    designation: "Assistant Professor",
    department: "CSE",
    email: "arunkumar.cse@siet.ac.in",
    teams_assigned: 2,
    specialization: "Embedded Systems & Robotics",
  },
  {
    id: "faculty-meenadevi",
    name: "Dr. Meena Devi",
    designation: "Professor",
    department: "CSE",
    email: "meenadevi.cse@siet.ac.in",
    teams_assigned: 3,
    specialization: "IoT & Cloud Computing",
  },
  {
    id: "faculty-rajesh",
    name: "Dr. K. Rajesh",
    designation: "Associate Professor",
    department: "CSE",
    email: "rajesh.cse@siet.ac.in",
    teams_assigned: 3,
    specialization: "Blockchain & Distributed Systems",
  },
  {
    id: "faculty-kavitha",
    name: "Dr. S. Kavitha",
    designation: "Associate Professor",
    department: "CSE",
    email: "kavitha.cse@siet.ac.in",
    teams_assigned: 3,
    specialization: "Computer Vision & Edge Computing",
  },
];

export const mockHodApprovals: HodApprovalRecord[] = [
  {
    id: "approval-001",
    team_name: "Team Gamma",
    team_id: "team-uuid-gamma-003",
    project_title: "IoT Sensor Fusion for Precision Agriculture & Irrigation",
    guide_name: "Dr. Meena Devi",
    type: "PROJECT_PROPOSAL",
    status: "PENDING",
    submitted_at: "2026-09-03T10:00:00Z",
    remarks: "Awaiting HOD review for domain relevance and feasibility.",
  },
  {
    id: "approval-002",
    team_name: "Team Zeta",
    team_id: "team-uuid-zeta-006",
    project_title: "Federated Learning Framework for Healthcare Data Privacy",
    guide_name: "Dr. Subramanian",
    type: "GUIDE_CHANGE",
    status: "PENDING",
    submitted_at: "2026-09-02T14:30:00Z",
    remarks: "Guide change from Dr. Arun Kumar to Dr. Subramanian for AI expertise alignment.",
  },
  {
    id: "approval-003",
    team_name: "Team Epsilon",
    team_id: "team-uuid-epsilon-005",
    project_title: "Edge Vision Defect Detection for Automotive Assembly Lines",
    guide_name: "Dr. S. Kavitha",
    type: "EXTENSION",
    status: "PENDING",
    submitted_at: "2026-09-01T09:15:00Z",
    remarks: "Requesting 2-week extension for hardware integration testing.",
  },
  {
    id: "approval-004",
    team_name: "Team Alpha",
    team_id: "team-uuid-alpha-001",
    project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
    guide_name: "Dr. Subramanian",
    type: "FINAL_SUBMISSION",
    status: "APPROVED",
    submitted_at: "2026-08-29T11:00:00Z",
    remarks: "Final submission approved. Cleared for viva voce evaluation.",
  },
  {
    id: "approval-005",
    team_name: "Team Beta",
    team_id: "team-uuid-beta-002",
    project_title: "Autonomous Drone Delivery for Hospital Supplies",
    guide_name: "Dr. Arun Kumar",
    type: "PROJECT_PROPOSAL",
    status: "APPROVED",
    submitted_at: "2026-08-25T16:00:00Z",
    remarks: "Proposal approved. Excellent problem statement and feasibility analysis.",
  },
  {
    id: "approval-006",
    team_name: "Team Delta",
    team_id: "team-uuid-delta-004",
    project_title: "Decentralized Credential Verification using Polygon",
    guide_name: "Dr. K. Rajesh",
    type: "FINAL_SUBMISSION",
    status: "REJECTED",
    submitted_at: "2026-08-28T10:30:00Z",
    remarks: "Report lacks formal smart contract security audit. Resubmit after revision.",
  },
];

// Additional mock teams for batch 2024-2028
export const mockHodTeams2024: AdvisorTeamSummary[] = [
  {
    team_id: "team-uuid-zeta-006",
    name: "Team Zeta",
    project_title: "Federated Learning Framework for Healthcare Data Privacy",
    batch: "2024-2028",
    section: "A",
    department: "Computer Science & Engineering",
    guide: {
      id: "faculty-subramanian",
      name: "Dr. Subramanian",
      full_name: "Dr. Subramanian",
      designation: "Professor",
      department: "CSE",
      email: "subramanian.cse@siet.ac.in",
    },
    members: [
      { id: "s-021", student_id: "s-021", roll_number: "24CS005", full_name: "Aditya Rajan", email: "aditya.24cs@siet.ac.in", is_team_leader: true, is_leader: true },
      { id: "s-022", student_id: "s-022", roll_number: "24CS012", full_name: "Lakshmi Priya", email: "lakshmi.24cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "s-023", student_id: "s-023", roll_number: "24CS019", full_name: "Suresh M", email: "suresh.24cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "s-024", student_id: "s-024", roll_number: "24CS027", full_name: "Kavya N", email: "kavya.24cs@siet.ac.in", is_team_leader: false, is_leader: false },
    ],
    members_names: ["Aditya Rajan (24CS005)", "Lakshmi Priya (24CS012)", "Suresh M (24CS019)", "Kavya N (24CS027)"],
    current_phase: "Phase I Review",
    submission_status: "SUBMITTED",
    evaluation_status: "PENDING",
    member_count: 4,
    leader: { id: "s-021", roll_number: "24CS005", full_name: "Aditya Rajan", email: "aditya.24cs@siet.ac.in", is_team_leader: true },
  },
  {
    team_id: "team-uuid-eta-007",
    name: "Team Eta",
    project_title: "Real-Time Sign Language Translation Using Transformer Models",
    batch: "2024-2028",
    section: "A",
    department: "Computer Science & Engineering",
    guide: {
      id: "faculty-kavitha",
      name: "Dr. S. Kavitha",
      full_name: "Dr. S. Kavitha",
      designation: "Associate Professor",
      department: "CSE",
      email: "kavitha.cse@siet.ac.in",
    },
    members: [
      { id: "s-025", student_id: "s-025", roll_number: "24CS031", full_name: "Deepak V", email: "deepak.24cs@siet.ac.in", is_team_leader: true, is_leader: true },
      { id: "s-026", student_id: "s-026", roll_number: "24CS038", full_name: "Revathi S", email: "revathi.24cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "s-027", student_id: "s-027", roll_number: "24CS044", full_name: "Ganesh R", email: "ganesh.24cs@siet.ac.in", is_team_leader: false, is_leader: false },
    ],
    members_names: ["Deepak V (24CS031)", "Revathi S (24CS038)", "Ganesh R (24CS044)"],
    current_phase: "Phase I Review",
    submission_status: "NOT_SUBMITTED",
    evaluation_status: "NOT_STARTED",
    member_count: 3,
    leader: { id: "s-025", roll_number: "24CS031", full_name: "Deepak V", email: "deepak.24cs@siet.ac.in", is_team_leader: true },
  },
  {
    team_id: "team-uuid-theta-008",
    name: "Team Theta",
    project_title: "Automated Code Review System Using LLMs and Static Analysis",
    batch: "2024-2028",
    section: "B",
    department: "Computer Science & Engineering",
    guide: {
      id: "faculty-rajesh",
      name: "Dr. K. Rajesh",
      full_name: "Dr. K. Rajesh",
      designation: "Associate Professor",
      department: "CSE",
      email: "rajesh.cse@siet.ac.in",
    },
    members: [
      { id: "s-028", student_id: "s-028", roll_number: "24CS052", full_name: "Nithya K", email: "nithya.24cs@siet.ac.in", is_team_leader: true, is_leader: true },
      { id: "s-029", student_id: "s-029", roll_number: "24CS058", full_name: "Vijay S", email: "vijay.24cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "s-030", student_id: "s-030", roll_number: "24CS065", full_name: "Preethi M", email: "preethi.24cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "s-031", student_id: "s-031", roll_number: "24CS071", full_name: "Kiran T", email: "kiran.24cs@siet.ac.in", is_team_leader: false, is_leader: false },
    ],
    members_names: ["Nithya K (24CS052)", "Vijay S (24CS058)", "Preethi M (24CS065)", "Kiran T (24CS071)"],
    current_phase: "Phase I Review",
    submission_status: "SUBMITTED",
    evaluation_status: "EVALUATED",
    evaluation: {
      id: "eval-uuid-008",
      team_score: 82,
      team_remarks: "Good conceptual framework. LLM integration needs further refinement.",
      status: "EVALUATED",
      created_at: "2026-08-28T10:00:00Z",
      strengths: "Strong static analysis pipeline, good documentation.",
      areas_for_improvement: "LLM prompt engineering needs optimization. Add benchmarks.",
      recommendation_status: "APPROVED",
      criteria_scores: { project: 17, technical: 16.5, presentation: 16, documentation: 16.5, contribution: 16 },
    },
    member_count: 4,
    leader: { id: "s-028", roll_number: "24CS052", full_name: "Nithya K", email: "nithya.24cs@siet.ac.in", is_team_leader: true },
  },
];

// Additional mock teams for batch 2025-2029
export const mockHodTeams2025: AdvisorTeamSummary[] = [
  {
    team_id: "team-uuid-iota-009",
    name: "Team Iota",
    project_title: "Smart Campus Energy Management with Renewable Integration",
    batch: "2025-2029",
    section: "A",
    department: "Computer Science & Engineering",
    guide: {
      id: "faculty-meenadevi",
      name: "Dr. Meena Devi",
      full_name: "Dr. Meena Devi",
      designation: "Professor",
      department: "CSE",
      email: "meenadevi.cse@siet.ac.in",
    },
    members: [
      { id: "s-032", student_id: "s-032", roll_number: "25CS003", full_name: "Ashwin R", email: "ashwin.25cs@siet.ac.in", is_team_leader: true, is_leader: true },
      { id: "s-033", student_id: "s-033", roll_number: "25CS010", full_name: "Shruthi K", email: "shruthi.25cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "s-034", student_id: "s-034", roll_number: "25CS018", full_name: "Ravi D", email: "ravi.25cs@siet.ac.in", is_team_leader: false, is_leader: false },
    ],
    members_names: ["Ashwin R (25CS003)", "Shruthi K (25CS010)", "Ravi D (25CS018)"],
    current_phase: "Abstract Submission",
    submission_status: "NOT_SUBMITTED",
    evaluation_status: "NOT_STARTED",
    member_count: 3,
    leader: { id: "s-032", roll_number: "25CS003", full_name: "Ashwin R", email: "ashwin.25cs@siet.ac.in", is_team_leader: true },
  },
  {
    team_id: "team-uuid-kappa-010",
    name: "Team Kappa",
    project_title: "Personalized Adaptive Learning Platform Using Knowledge Graphs",
    batch: "2025-2029",
    section: "A",
    department: "Computer Science & Engineering",
    guide: {
      id: "faculty-subramanian",
      name: "Dr. Subramanian",
      full_name: "Dr. Subramanian",
      designation: "Professor",
      department: "CSE",
      email: "subramanian.cse@siet.ac.in",
    },
    members: [
      { id: "s-035", student_id: "s-035", roll_number: "25CS022", full_name: "Bala M", email: "bala.25cs@siet.ac.in", is_team_leader: true, is_leader: true },
      { id: "s-036", student_id: "s-036", roll_number: "25CS030", full_name: "Janani S", email: "janani.25cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "s-037", student_id: "s-037", roll_number: "25CS038", full_name: "Sathish P", email: "sathish.25cs@siet.ac.in", is_team_leader: false, is_leader: false },
      { id: "s-038", student_id: "s-038", roll_number: "25CS045", full_name: "Meena R", email: "meena.25cs@siet.ac.in", is_team_leader: false, is_leader: false },
    ],
    members_names: ["Bala M (25CS022)", "Janani S (25CS030)", "Sathish P (25CS038)", "Meena R (25CS045)"],
    current_phase: "Abstract Submission",
    submission_status: "NOT_SUBMITTED",
    evaluation_status: "NOT_STARTED",
    member_count: 4,
    leader: { id: "s-035", roll_number: "25CS022", full_name: "Bala M", email: "bala.25cs@siet.ac.in", is_team_leader: true },
  },
];

/**
 * Convenience: all HOD teams across all batches
 */
export function getAllHodTeams(): AdvisorTeamSummary[] {
  return [...mockAdvisorTeams, ...mockHodTeams2024, ...mockHodTeams2025];
}

export function getHodTeamsByBatch(batch: string): AdvisorTeamSummary[] {
  const all = getAllHodTeams();
  if (!batch || batch === "all") return all;
  return all.filter((t) => t.batch === batch);
}

