# A generic, single database configuration.

[alembic]
# path to migration script
script_location = alembic

# template used to generate migration file names
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters which are allowed to be in a 'slug'
# max_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a corresponding .py file to be detected as revisions in the versions/ dir
# sourceless = false

# version location specification; This defaults
# to alembic/versions. When using multiple version
# directories, initial revisions must be created with --version-path.
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# version path separator; As mentioned above, this is the character(s) used to split
# the version_locations. The default setting is space.
# version_path_separator = :

# set to 'true' to search source files recursively
# recursive_version_locations = false

# the output encoding used when revision files are written from script.py.mako
# output_encoding = utf-8

# sqlalchemy.url is dynamically loaded from environment settings in alembic/env.py


[post_write_hooks]

[loggers]
keys = root, alembic, sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
