import {
  HodDashboardSummary,
  HodMilestoneStage,
  AttentionRequiredItem,
  LiveActivityEvent,
  HodAdvisorRecord,
  AdvisorEvaluationHistoryRecord,
  AssignmentChangeRecord,
  AdvisorComplianceRecord,
} from "@/types/hod";

// ============================================================================
// MOCK DATASETS FOR OFFLINE & STANDALONE EXECUTION
// ============================================================================

export const mockDashboardSummary: HodDashboardSummary = {
  students_count: 240,
  teams_count: 48,
  advisors_count: 12,
  guides_count: 18,
  health: {
    on_track: 36,
    at_risk: 9,
    critical: 3,
  },
  avg_score: 86.4,
  evaluated_teams_count: 42,
};

export const mockMilestoneStages: HodMilestoneStage[] = [
  {
    id: "stg-1",
    stage_number: 1,
    title: "Problem Definition & Literature Survey",
    weightage_percent: 10,
    completed_teams: 48,
    total_teams: 48,
    status: "COMPLETED",
    due_date: "15 Jul 2026",
  },
  {
    id: "stg-2",
    stage_number: 2,
    title: "System Architecture & Design",
    weightage_percent: 15,
    completed_teams: 48,
    total_teams: 48,
    status: "COMPLETED",
    due_date: "10 Aug 2026",
  },
  {
    id: "stg-3",
    stage_number: 3,
    title: "Intermediate Implementation & Progress",
    weightage_percent: 20,
    completed_teams: 44,
    total_teams: 48,
    status: "IN_PROGRESS",
    due_date: "05 Sep 2026",
  },
  {
    id: "stg-4",
    stage_number: 4,
    title: "Complete Technical Implementation",
    weightage_percent: 25,
    completed_teams: 26,
    total_teams: 48,
    status: "IN_PROGRESS",
    due_date: "25 Sep 2026",
  },
  {
    id: "stg-5",
    stage_number: 5,
    title: "Pre-Submission Testing & Documentation",
    weightage_percent: 15,
    completed_teams: 0,
    total_teams: 48,
    status: "NOT_STARTED",
    due_date: "15 Oct 2026",
  },
  {
    id: "stg-6",
    stage_number: 6,
    title: "Final Viva Voce & Project Defense",
    weightage_percent: 15,
    completed_teams: 0,
    total_teams: 48,
    status: "NOT_STARTED",
    due_date: "05 Nov 2026",
  },
];

export const mockAttentionItems: AttentionRequiredItem[] = [
  {
    id: "att-1",
    severity: "CRITICAL",
    title: "Advisor Evaluation Overdue (> 7 Days)",
    description:
      "Prof. S. Suresh has 3 team evaluations pending past the institutional review window for Stage 4 deliverables.",
    action_label: "Review Advisor Delays →",
    action_link: "/hod/advisors",
  },
  {
    id: "att-2",
    severity: "HIGH",
    title: "PRC Quality Alert: Score Below 50% Threshold",
    description:
      "Team QuantumCipher (ECE-Sec B) received 8.5/20 on Intermediate Implementation. Mandatory remedial review required.",
    action_label: "Inspect Team Dossier →",
    action_link: "/hod/advisors/adv-2/teams/team-qc",
  },
  {
    id: "att-3",
    severity: "MEDIUM",
    title: "Admin Guide Reallocation Recorded",
    description:
      "Central Admin reallocated Dr. P. Suresh to Team RoboTech following faculty medical leave.",
    action_label: "View Change Audit →",
    action_link: "/hod/change-history",
  },
];

export const mockLiveActivityStream: LiveActivityEvent[] = [
  {
    id: "act-1",
    actor_name: "Dr. A. Nandhini",
    actor_role: "Faculty Advisor",
    action: "evaluated deliverable Stage 3 for",
    target_name: "Team NeuroSync (19/20)",
    timestamp: "12 minutes ago",
  },
  {
    id: "act-2",
    actor_name: "Central Admin",
    actor_role: "System Administrator",
    action: "updated guide assignment for",
    target_name: "Team RoboTech",
    timestamp: "48 minutes ago",
  },
  {
    id: "act-3",
    actor_name: "Dr. M. K. Raman",
    actor_role: "Faculty Advisor",
    action: "published marksheet for",
    target_name: "Team SolarSense (17.5/20)",
    timestamp: "2 hours ago",
  },
  {
    id: "act-4",
    actor_name: "Dr. K. Senthil Kumar",
    actor_role: "Faculty Advisor",
    action: "completed evaluation cycle for",
    target_name: "4 Teams in CSE-A",
    timestamp: "3 hours ago",
  },
  {
    id: "act-5",
    actor_name: "Prof. S. Suresh",
    actor_role: "Faculty Advisor",
    action: "requested re-upload of block diagram from",
    target_name: "Team VisionAI",
    timestamp: "5 hours ago",
  },
];

export const mockAdvisorsList: HodAdvisorRecord[] = [
  // Faculty Advisors & Guides
  {
    id: "adv-1",
    name: "Dr. K. Senthil Kumar",
    faculty_id: "SIET-FAC-0012",
    role: "BOTH",
    designation: "Associate Professor",
    department: "Computer Science & Engineering",
    email: "senthilkumar.k@siet.ac.in",
    phone: "+91 94432 18901",
    batch: "2025–2029",
    teams_count: 4,
    students_count: 16,
    evaluations_completed: 16,
    evaluations_pending: 0,
    completion_rate: 100,
    assigned_teams: [
      {
        id: "team-uuid-alpha-001",
        name: "Team Alpha",
        project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
        guide_name: "Dr. Subramanian",
        advisor_name: "Dr. K. Senthil Kumar",
        members_count: 4,
        status: "EVALUATED",
        score: 88,
        stage: "Stage 1",
        enrolled_members: [
          { name: "Rahul Sharma", roll_number: "23CS001", department: "CSE", role: "Core Contributor" },
          { name: "Priya Dharshini", roll_number: "23CS014", department: "CSE", role: "Core Contributor" },
          { name: "Karthik Raja", roll_number: "23CS028", department: "CSE", role: "Core Contributor" },
          { name: "Ananya Iyer", roll_number: "23CS042", department: "CSE", role: "Core Contributor" },
        ],
      },
      {
        id: "team-uuid-beta-002",
        name: "Team Beta",
        project_title: "Autonomous Drone Delivery for Hospital Supplies",
        guide_name: "Dr. Arun Kumar",
        advisor_name: "Dr. K. Senthil Kumar",
        members_count: 4,
        status: "EVALUATED",
        score: 95,
        stage: "Stage 1",
        enrolled_members: [
          { name: "Vikram Malhotra", roll_number: "23CS051", department: "CSE", role: "Core Contributor" },
          { name: "Sneha Reddy", roll_number: "23CS062", department: "CSE", role: "Core Contributor" },
          { name: "Arjun Verma", roll_number: "23CS074", department: "CSE", role: "Core Contributor" },
          { name: "Divya Nair", roll_number: "23CS089", department: "CSE", role: "Core Contributor" },
        ],
      },
      {
        id: "team-uuid-gamma-003",
        name: "Team Gamma",
        project_title: "IoT Sensor Fusion for Precision Agriculture",
        guide_name: "Dr. Meena Devi",
        advisor_name: "Dr. K. Senthil Kumar",
        members_count: 4,
        status: "EVALUATED",
        score: 90,
        stage: "Stage 1",
        enrolled_members: [
          { name: "Gokul Prasad", roll_number: "23CS095", department: "CSE", role: "Core Contributor" },
          { name: "Nandhini R", roll_number: "23CS102", department: "CSE", role: "Core Contributor" },
          { name: "Suresh Kumar", roll_number: "23CS114", department: "CSE", role: "Core Contributor" },
          { name: "Swathi M", roll_number: "23CS126", department: "CSE", role: "Core Contributor" },
        ],
      },
      {
        id: "team-uuid-delta-004",
        name: "Team Delta",
        project_title: "Decentralized Credential Verification using Blockchain",
        guide_name: "Dr. K. Rajesh",
        advisor_name: "Dr. K. Senthil Kumar",
        members_count: 4,
        status: "EVALUATED",
        score: 88,
        stage: "Stage 1",
        enrolled_members: [
          { name: "Rohan Das", roll_number: "23CS133", department: "CSE", role: "Core Contributor" },
          { name: "Keerthana B", roll_number: "23CS145", department: "CSE", role: "Core Contributor" },
          { name: "Manoj K", roll_number: "23CS156", department: "CSE", role: "Core Contributor" },
          { name: "Pavithra V", roll_number: "23CS168", department: "CSE", role: "Core Contributor" },
        ],
      },
    ],
  },
  {
    id: "adv-2",
    name: "Dr. A. Nandhini",
    faculty_id: "SIET-FAC-0018",
    role: "BOTH",
    designation: "Professor",
    department: "Electrical & Electronics Engineering",
    email: "nandhini.a@siet.ac.in",
    phone: "+91 98421 67234",
    batch: "2025–2029",
    teams_count: 4,
    students_count: 16,
    evaluations_completed: 14,
    evaluations_pending: 2,
    completion_rate: 87.5,
    assigned_teams: [
      {
        id: "team-neuro",
        name: "Team NeuroSync",
        project_title: "Neuromorphic Edge Processor for EEG Spike Detection",
        guide_name: "Dr. V. Rajesh",
        advisor_name: "Dr. A. Nandhini",
        members_count: 4,
        status: "EVALUATED",
        score: 91,
        stage: "Stage 3",
        enrolled_members: [
          { name: "Aravind R", roll_number: "25EC001", department: "ECE", role: "Core Contributor" },
          { name: "Bhavana S", roll_number: "25EC014", department: "ECE", role: "Core Contributor" },
          { name: "Dinesh K", roll_number: "25EC028", department: "ECE", role: "Core Contributor" },
          { name: "Harini M", roll_number: "25EC042", department: "ECE", role: "Core Contributor" },
        ],
      },
      {
        id: "team-solar",
        name: "Team SolarSense",
        project_title: "IoT Dual-Axis Solar Tracking with Maximum Power Point",
        guide_name: "Dr. V. Rajesh",
        advisor_name: "Dr. A. Nandhini",
        members_count: 4,
        status: "EVALUATED",
        score: 87.5,
        stage: "Stage 3",
        enrolled_members: [
          { name: "Karthik V", roll_number: "25EE011", department: "EEE", role: "Core Contributor" },
          { name: "Meena L", roll_number: "25EE024", department: "EEE", role: "Core Contributor" },
          { name: "Naveen P", roll_number: "25EE037", department: "EEE", role: "Core Contributor" },
          { name: "Pooja S", roll_number: "25EE049", department: "EEE", role: "Core Contributor" },
        ],
      },
      {
        id: "team-qc",
        name: "Team QuantumCipher",
        project_title: "Post-Quantum Cryptographic Co-Processor in FPGA",
        guide_name: "Dr. S. Ramesh",
        advisor_name: "Dr. A. Nandhini",
        members_count: 4,
        status: "PENDING",
        score: 42.5,
        stage: "Stage 2",
      },
      {
        id: "team-echo",
        name: "Team EchoGrid",
        project_title: "Acoustic Sensor Mesh for Industrial Pipeline Leakage",
        guide_name: "Dr. S. Ramesh",
        advisor_name: "Dr. A. Nandhini",
        members_count: 4,
        status: "PENDING",
        stage: "Stage 3",
      },
    ],
  },
  {
    id: "adv-3",
    name: "Prof. S. Suresh",
    faculty_id: "SIET-FAC-0025",
    role: "ADVISOR",
    designation: "Assistant Professor (Sr. Grade)",
    department: "Computer Science & Engineering",
    email: "suresh.s@siet.ac.in",
    phone: "+91 97890 54312",
    batch: "2025–2029",
    teams_count: 4,
    students_count: 16,
    evaluations_completed: 8,
    evaluations_pending: 8,
    completion_rate: 50.0,
    assigned_teams: [
      {
        id: "team-vision",
        name: "Team VisionAI",
        project_title: "Low-Latency Object Tracking for Autonomous AGVs",
        guide_name: "Dr. P. Suresh",
        advisor_name: "Prof. S. Suresh",
        members_count: 4,
        status: "OVERDUE",
        stage: "Stage 3",
      },
      {
        id: "team-robo",
        name: "Team RoboTech",
        project_title: "Swarm Robotics for Disaster Search & Rescue",
        guide_name: "Dr. P. Suresh",
        advisor_name: "Prof. S. Suresh",
        members_count: 4,
        status: "OVERDUE",
        stage: "Stage 3",
      },
      {
        id: "team-cyber",
        name: "Team CyberShield",
        project_title: "Zero-Trust SCADA Network Intrusion Prevention",
        guide_name: "Dr. M. Senthil Nathan",
        advisor_name: "Prof. S. Suresh",
        members_count: 4,
        status: "OVERDUE",
        stage: "Stage 3",
      },
      {
        id: "team-aero",
        name: "Team AeroSense",
        project_title: "UAV Airborne LiDAR for Precision Forest Canopy Mapping",
        guide_name: "Dr. M. Senthil Nathan",
        advisor_name: "Prof. S. Suresh",
        members_count: 4,
        status: "EVALUATED",
        score: 80,
        stage: "Stage 3",
      },
    ],
  },
  {
    id: "adv-4",
    name: "Dr. M. K. Raman",
    faculty_id: "SIET-FAC-0031",
    role: "ADVISOR",
    designation: "Associate Professor",
    department: "Computer Science & Engineering",
    email: "raman.mk@siet.ac.in",
    phone: "+91 94422 99881",
    batch: "2025–2029",
    teams_count: 4,
    students_count: 16,
    evaluations_completed: 16,
    evaluations_pending: 0,
    completion_rate: 100,
    assigned_teams: [
      {
        id: "team-med",
        name: "Team MedTech",
        project_title: "Wearable Non-Invasive Continuous Glucose Monitor",
        guide_name: "Dr. T. Geetha",
        advisor_name: "Dr. M. K. Raman",
        members_count: 4,
        status: "EVALUATED",
        score: 90,
        stage: "Stage 3",
      },
      {
        id: "team-agri",
        name: "Team AgroBot",
        project_title: "Autonomous Weed Detection & Targeted Herbicide Rover",
        guide_name: "Dr. T. Geetha",
        advisor_name: "Dr. M. K. Raman",
        members_count: 4,
        status: "EVALUATED",
        score: 87.5,
        stage: "Stage 3",
      },
      {
        id: "team-grid",
        name: "Team SmartGrid",
        project_title: "Blockchain Enabled P2P Solar Energy Trading",
        guide_name: "Dr. R. Kavitha",
        advisor_name: "Dr. M. K. Raman",
        members_count: 4,
        status: "EVALUATED",
        score: 97.5,
        stage: "Stage 3",
      },
      {
        id: "team-secure",
        name: "Team SecurePass",
        project_title: "Biometric Keystroke Dynamics Authentication",
        guide_name: "Dr. R. Kavitha",
        advisor_name: "Dr. M. K. Raman",
        members_count: 4,
        status: "EVALUATED",
        score: 90,
        stage: "Stage 3",
      },
    ],
  },
  // Dedicated Project Guides
  {
    id: "gd-1",
    name: "Dr. Subramanian",
    faculty_id: "SIET-FAC-0005",
    role: "GUIDE",
    designation: "Professor",
    department: "Computer Science & Engineering",
    email: "subramanian.p@siet.ac.in",
    phone: "+91 98401 22334",
    batch: "2025–2029",
    teams_count: 4,
    students_count: 16,
    evaluations_completed: 16,
    evaluations_pending: 0,
    completion_rate: 100,
    assigned_teams: [
      {
        id: "team-uuid-alpha-001",
        name: "Team Alpha",
        project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
        guide_name: "Dr. Subramanian",
        advisor_name: "Dr. K. Senthil Kumar",
        members_count: 4,
        status: "EVALUATED",
        score: 88,
        stage: "Stage 1",
        enrolled_members: [
          { name: "Rahul Sharma", roll_number: "23CS001", department: "CSE", role: "Core Contributor" },
          { name: "Priya Dharshini", roll_number: "23CS014", department: "CSE", role: "Core Contributor" },
          { name: "Karthik Raja", roll_number: "23CS028", department: "CSE", role: "Core Contributor" },
          { name: "Ananya Iyer", roll_number: "23CS042", department: "CSE", role: "Core Contributor" },
        ],
      },
    ],
  },
  {
    id: "gd-2",
    name: "Dr. Arun Kumar",
    faculty_id: "SIET-FAC-0029",
    role: "GUIDE",
    designation: "Assistant Professor",
    department: "Computer Science & Engineering",
    email: "arunkumar.c@siet.ac.in",
    phone: "+91 97891 77665",
    batch: "2025–2029",
    teams_count: 3,
    students_count: 12,
    evaluations_completed: 12,
    evaluations_pending: 0,
    completion_rate: 100,
    assigned_teams: [
      {
        id: "team-uuid-beta-002",
        name: "Team Beta",
        project_title: "Autonomous Drone Delivery for Hospital Supplies",
        guide_name: "Dr. Arun Kumar",
        advisor_name: "Dr. K. Senthil Kumar",
        members_count: 4,
        status: "EVALUATED",
        score: 95,
        stage: "Stage 1",
      },
    ],
  },
  {
    id: "gd-3",
    name: "Dr. Meena Devi",
    faculty_id: "SIET-FAC-0014",
    role: "GUIDE",
    designation: "Professor",
    department: "Computer Science & Engineering",
    email: "meenadevi.m@siet.ac.in",
    phone: "+91 94441 55667",
    batch: "2025–2029",
    teams_count: 3,
    students_count: 12,
    evaluations_completed: 12,
    evaluations_pending: 0,
    completion_rate: 100,
    assigned_teams: [
      {
        id: "team-uuid-gamma-003",
        name: "Team Gamma",
        project_title: "IoT Sensor Fusion for Precision Agriculture",
        guide_name: "Dr. Meena Devi",
        advisor_name: "Dr. K. Senthil Kumar",
        members_count: 4,
        status: "EVALUATED",
        score: 90,
        stage: "Stage 1",
      },
    ],
  },
  {
    id: "gd-4",
    name: "Dr. K. Rajesh",
    faculty_id: "SIET-FAC-0019",
    role: "GUIDE",
    designation: "Associate Professor",
    department: "Computer Science & Engineering",
    email: "rajesh.k@siet.ac.in",
    phone: "+91 98433 99887",
    batch: "2025–2029",
    teams_count: 4,
    students_count: 16,
    evaluations_completed: 16,
    evaluations_pending: 0,
    completion_rate: 100,
    assigned_teams: [
      {
        id: "team-uuid-delta-004",
        name: "Team Delta",
        project_title: "Decentralized Credential Verification using Blockchain",
        guide_name: "Dr. K. Rajesh",
        advisor_name: "Dr. K. Senthil Kumar",
        members_count: 4,
        status: "EVALUATED",
        score: 88,
        stage: "Stage 1",
      },
    ],
  },
  {
    id: "gd-5",
    name: "Dr. M. Senthil Nathan",
    faculty_id: "SIET-FAC-0008",
    role: "GUIDE",
    designation: "Professor",
    department: "Computer Science & Engineering",
    email: "senthilnathan.m@siet.ac.in",
    phone: "+91 94435 88990",
    batch: "2025–2029",
    teams_count: 4,
    students_count: 16,
    evaluations_completed: 14,
    evaluations_pending: 2,
    completion_rate: 87.5,
    assigned_teams: [],
  },
  {
    id: "gd-6",
    name: "Dr. P. Suresh",
    faculty_id: "SIET-FAC-0015",
    role: "GUIDE",
    designation: "Professor",
    department: "Computer Science & Engineering",
    email: "suresh.p@siet.ac.in",
    phone: "+91 94448 33445",
    batch: "2025–2029",
    teams_count: 4,
    students_count: 16,
    evaluations_completed: 12,
    evaluations_pending: 4,
    completion_rate: 75.0,
    assigned_teams: [],
  },
  {
    id: "gd-7",
    name: "Dr. V. Rajesh",
    faculty_id: "SIET-FAC-0022",
    role: "GUIDE",
    designation: "Associate Professor",
    department: "Electronics & Communication Engineering",
    email: "rajesh.v@siet.ac.in",
    phone: "+91 98411 77889",
    batch: "2025–2029",
    teams_count: 3,
    students_count: 12,
    evaluations_completed: 12,
    evaluations_pending: 0,
    completion_rate: 100,
    assigned_teams: [],
  },
];

// ============================================================================
// EVALUATION SESSIONS AUDIT RECORDS (Matches Screenshot 1, 2, 3 Exactly)
// ============================================================================

export const mockEvaluationHistoryRecords: AdvisorEvaluationHistoryRecord[] = [
  // Session 1: Saturday, August 29, 2026 - 3:30 PM (4 Teams)
  {
    id: "eval-rec-sat-1",
    advisor_id: "adv-1",
    advisor_name: "Dr. K. Senthil Kumar",
    batch: "2025–2029",
    team_id: "team-uuid-alpha-001",
    team_name: "Team Alpha",
    project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
    guide_name: "Dr. Subramanian",
    guide_designation: "Professor",
    guide_department: "CSE",
    evaluation_stage: "Stage 1",
    session_label: "Official PRC Examination Session",
    students: [
      "Rahul Sharma (23CS001)",
      "Priya Dharshini (23CS014)",
      "Karthik Raja (23CS028)",
      "Ananya Iyer (23CS042)",
    ],
    enrolled_members: [
      { name: "Rahul Sharma", roll_number: "23CS001", department: "CSE", role: "Core Contributor" },
      { name: "Priya Dharshini", roll_number: "23CS014", department: "CSE", role: "Core Contributor" },
      { name: "Karthik Raja", roll_number: "23CS028", department: "CSE", role: "Core Contributor" },
      { name: "Ananya Iyer", roll_number: "23CS042", department: "CSE", role: "Core Contributor" },
    ],
    submission_date: "28 Aug 2026",
    submission_time: "15:00",
    evaluation_date: "Saturday, August 29, 2026",
    evaluation_time: "3:30 PM",
    marks_awarded: 88,
    max_marks: 100,
    status: "EVALUATED",
    feedback:
      "Exceptional architecture, robust code repository, and thorough literature review. Meets all autonomous college guidelines.",
    standout_strengths:
      "Comprehensive architecture, clean modular code structure, and strong literature survey.",
    areas_for_improvement:
      "Expand automated test coverage and include benchmark latency graphs in the final appendix.",
    criteria_scores: {
      project_execution: 19,
      technical_depth: 18.5,
      presentation_viva: 18,
      documentation: 14.5,
      contribution: 18,
      problem_definition: 4.8,
      technical_implementation: 4.5,
      innovation: 4.2,
      presentation: 4.5,
    },
    submitted_content: {
      abstract:
        "AI-Powered Smart Attendance & Campus Surveillance System incorporating face recognition via DeepFace and YOLOv8 real-time edge streaming.",
      files: [
        { name: "Architecture_Design_Doc.pdf", size: "3.4 MB", type: "PDF" },
        { name: "Literature_Review_Scopus.pdf", size: "1.8 MB", type: "PDF" },
      ],
      github_url: "https://github.com/siet-cse/smart-campus-surveillance",
      demo_url: "https://campus-ai.siet.edu.in",
    },
  },
  {
    id: "eval-rec-sat-2",
    advisor_id: "adv-1",
    advisor_name: "Dr. K. Senthil Kumar",
    batch: "2025–2029",
    team_id: "team-uuid-beta-002",
    team_name: "Team Beta",
    project_title: "Autonomous Drone Delivery for Hospital Supplies",
    guide_name: "Dr. Arun Kumar",
    guide_designation: "Assistant Professor",
    guide_department: "CSE",
    evaluation_stage: "Stage 1",
    session_label: "Official PRC Examination Session",
    students: [
      "Vikram Malhotra (23CS051)",
      "Sneha Reddy (23CS062)",
      "Arjun Verma (23CS074)",
      "Divya Nair (23CS089)",
    ],
    enrolled_members: [
      { name: "Vikram Malhotra", roll_number: "23CS051", department: "CSE", role: "Core Contributor" },
      { name: "Sneha Reddy", roll_number: "23CS062", department: "CSE", role: "Core Contributor" },
      { name: "Arjun Verma", roll_number: "23CS074", department: "CSE", role: "Core Contributor" },
      { name: "Divya Nair", roll_number: "23CS089", department: "CSE", role: "Core Contributor" },
    ],
    submission_date: "28 Aug 2026",
    submission_time: "16:20",
    evaluation_date: "Saturday, August 29, 2026",
    evaluation_time: "3:30 PM",
    marks_awarded: 95,
    max_marks: 100,
    status: "EVALUATED",
    feedback:
      "Outstanding hardware-in-the-loop simulation. Autopilot waypoint navigation demonstrated zero GPS drift.",
    standout_strengths:
      "High reliability autonomous path planning and fail-safe return-to-launch protocol.",
    areas_for_improvement:
      "Add battery thermal degradation metrics during payload delivery simulations.",
    criteria_scores: {
      project_execution: 19.5,
      technical_depth: 19.5,
      presentation_viva: 19,
      documentation: 18,
      contribution: 19,
    },
    submitted_content: {
      abstract:
        "Autonomous UAV payload delivery mechanism with fail-safe telemetry and obstacle avoidance for rapid intra-hospital blood pouch transport.",
      files: [{ name: "UAV_Medical_Delivery_Report.pdf", size: "4.2 MB", type: "PDF" }],
      github_url: "https://github.com/siet-cse/hospital-uav-drone",
    },
  },
  {
    id: "eval-rec-sat-3",
    advisor_id: "adv-1",
    advisor_name: "Dr. K. Senthil Kumar",
    batch: "2025–2029",
    team_id: "team-uuid-gamma-003",
    team_name: "Team Gamma",
    project_title: "IoT Sensor Fusion for Precision Agriculture",
    guide_name: "Dr. Meena Devi",
    guide_designation: "Professor",
    guide_department: "CSE",
    evaluation_stage: "Stage 1",
    session_label: "Official PRC Examination Session",
    students: [
      "Gokul Prasad (23CS095)",
      "Nandhini R (23CS102)",
      "Suresh Kumar (23CS114)",
      "Swathi M (23CS126)",
    ],
    enrolled_members: [
      { name: "Gokul Prasad", roll_number: "23CS095", department: "CSE", role: "Core Contributor" },
      { name: "Nandhini R", roll_number: "23CS102", department: "CSE", role: "Core Contributor" },
      { name: "Suresh Kumar", roll_number: "23CS114", department: "CSE", role: "Core Contributor" },
      { name: "Swathi M", roll_number: "23CS126", department: "CSE", role: "Core Contributor" },
    ],
    submission_date: "28 Aug 2026",
    submission_time: "17:15",
    evaluation_date: "Saturday, August 29, 2026",
    evaluation_time: "3:30 PM",
    marks_awarded: 90,
    max_marks: 100,
    status: "EVALUATED",
    feedback:
      "LoRaWAN node energy budget is well calculated. Soil moisture calibration curves verified with standard sensor probes.",
    standout_strengths:
      "Low power sleep modes and ruggedized outdoor sensor packaging.",
    areas_for_improvement:
      "Document the mesh relay packet loss under dense crop canopy conditions.",
    criteria_scores: {
      project_execution: 18,
      technical_depth: 18.5,
      presentation_viva: 18,
      documentation: 17.5,
      contribution: 18,
    },
    submitted_content: {
      abstract:
        "Low-power LoRaWAN soil telemetry network optimizing micro-drip irrigation using machine learning predictive evapotranspiration models.",
      files: [{ name: "Precision_Agri_Sensor_Report.pdf", size: "3.1 MB", type: "PDF" }],
    },
  },
  {
    id: "eval-rec-sat-4",
    advisor_id: "adv-1",
    advisor_name: "Dr. K. Senthil Kumar",
    batch: "2025–2029",
    team_id: "team-uuid-delta-004",
    team_name: "Team Delta",
    project_title: "Decentralized Credential Verification using Blockchain",
    guide_name: "Dr. K. Rajesh",
    guide_designation: "Associate Professor",
    guide_department: "CSE",
    evaluation_stage: "Stage 1",
    session_label: "Official PRC Examination Session",
    students: [
      "Rohan Das (23CS133)",
      "Keerthana B (23CS145)",
      "Manoj K (23CS156)",
      "Pavithra V (23CS168)",
    ],
    enrolled_members: [
      { name: "Rohan Das", roll_number: "23CS133", department: "CSE", role: "Core Contributor" },
      { name: "Keerthana B", roll_number: "23CS145", department: "CSE", role: "Core Contributor" },
      { name: "Manoj K", roll_number: "23CS156", department: "CSE", role: "Core Contributor" },
      { name: "Pavithra V", roll_number: "23CS168", department: "CSE", role: "Core Contributor" },
    ],
    submission_date: "28 Aug 2026",
    submission_time: "18:00",
    evaluation_date: "Saturday, August 29, 2026",
    evaluation_time: "3:30 PM",
    marks_awarded: 88,
    max_marks: 100,
    status: "EVALUATED",
    feedback:
      "Ethereum smart contract gas benchmarks are acceptable. Zero-knowledge proof verification satisfies academic integrity constraints.",
    standout_strengths:
      "Clean smart contract architecture and IPFS metadata pinning.",
    areas_for_improvement:
      "Conduct security audit using Slither static analysis and present the report.",
    criteria_scores: {
      project_execution: 17.5,
      technical_depth: 18,
      presentation_viva: 17.5,
      documentation: 17,
      contribution: 18,
    },
    submitted_content: {
      abstract:
        "Tamper-proof academic diploma verification system leveraging Polygon Layer-2 smart contracts and decentralized DID resolvers.",
      files: [{ name: "Blockchain_Credential_Paper.pdf", size: "2.8 MB", type: "PDF" }],
    },
  },

  // Session 2: Friday, August 28, 2026 - 11:00 AM (3 Teams)
  {
    id: "eval-rec-fri-1",
    advisor_id: "adv-2",
    advisor_name: "Dr. A. Nandhini",
    batch: "2025–2029",
    team_id: "team-neuro",
    team_name: "Team NeuroSync",
    project_title: "Neuromorphic Edge Processor for EEG Spike Detection",
    guide_name: "Dr. V. Rajesh",
    guide_designation: "Associate Professor",
    guide_department: "ECE",
    evaluation_stage: "Stage 2",
    session_label: "Official PRC Examination Session",
    students: ["Aravind R", "Bhavana S", "Dinesh K", "Harini M"],
    submission_date: "27 Aug 2026",
    submission_time: "14:00",
    evaluation_date: "Friday, August 28, 2026",
    evaluation_time: "11:00 AM",
    marks_awarded: 91,
    max_marks: 100,
    status: "EVALUATED",
    feedback: "Exceptional asynchronous circuit simulation.",
    criteria_scores: {
      project_execution: 18.5,
      technical_depth: 19,
      presentation_viva: 18,
      documentation: 17.5,
      contribution: 18,
    },
  },
  {
    id: "eval-rec-fri-2",
    advisor_id: "adv-2",
    advisor_name: "Dr. A. Nandhini",
    batch: "2025–2029",
    team_id: "team-solar",
    team_name: "Team SolarSense",
    project_title: "IoT Dual-Axis Solar Tracking with Maximum Power Point",
    guide_name: "Dr. V. Rajesh",
    guide_designation: "Associate Professor",
    guide_department: "ECE",
    evaluation_stage: "Stage 2",
    session_label: "Official PRC Examination Session",
    students: ["Karthik V", "Meena L", "Naveen P", "Pooja S"],
    submission_date: "27 Aug 2026",
    submission_time: "15:30",
    evaluation_date: "Friday, August 28, 2026",
    evaluation_time: "11:00 AM",
    marks_awarded: 87.5,
    max_marks: 100,
    status: "EVALUATED",
    feedback: "Good servo tracking precision and MPPT response.",
    criteria_scores: {
      project_execution: 17.5,
      technical_depth: 18,
      presentation_viva: 17.5,
      documentation: 17,
      contribution: 17.5,
    },
  },
  {
    id: "eval-rec-fri-3",
    advisor_id: "adv-2",
    advisor_name: "Dr. A. Nandhini",
    batch: "2025–2029",
    team_id: "team-echo",
    team_name: "Team EchoGrid",
    project_title: "Acoustic Sensor Mesh for Industrial Pipeline Leakage",
    guide_name: "Dr. S. Ramesh",
    guide_designation: "Associate Professor",
    guide_department: "EEE",
    evaluation_stage: "Stage 2",
    session_label: "Official PRC Examination Session",
    students: ["Siddharth M", "Lakshmi N", "Vignesh T", "Anusha K"],
    submission_date: "27 Aug 2026",
    submission_time: "16:45",
    evaluation_date: "Friday, August 28, 2026",
    evaluation_time: "11:00 AM",
    marks_awarded: 85,
    max_marks: 100,
    status: "EVALUATED",
    feedback: "Acoustic signal envelope analysis performed well.",
    criteria_scores: {
      project_execution: 17,
      technical_depth: 17,
      presentation_viva: 17,
      documentation: 17,
      contribution: 17,
    },
  },

  // Session 3: Wednesday, August 26, 2026 - 2:15 PM (5 Teams)
  {
    id: "eval-rec-wed-1",
    advisor_id: "adv-4",
    advisor_name: "Dr. M. K. Raman",
    batch: "2025–2029",
    team_id: "team-med",
    team_name: "Team MedTech",
    project_title: "Wearable Non-Invasive Continuous Glucose Monitor",
    guide_name: "Dr. T. Geetha",
    guide_designation: "Associate Professor",
    guide_department: "CSE",
    evaluation_stage: "Stage 1",
    session_label: "Official PRC Examination Session",
    students: ["Pranathi S", "Varun M", "Aakash G", "Deepa B"],
    submission_date: "25 Aug 2026",
    submission_time: "11:00",
    evaluation_date: "Wednesday, August 26, 2026",
    evaluation_time: "2:15 PM",
    marks_awarded: 90,
    max_marks: 100,
    status: "EVALUATED",
    feedback: "Optical absorption modeling is thoroughly documented.",
    criteria_scores: {
      project_execution: 18,
      technical_depth: 18,
      presentation_viva: 18,
      documentation: 18,
      contribution: 18,
    },
  },
  {
    id: "eval-rec-wed-2",
    advisor_id: "adv-4",
    advisor_name: "Dr. M. K. Raman",
    batch: "2025–2029",
    team_id: "team-agri",
    team_name: "Team AgroBot",
    project_title: "Autonomous Weed Detection & Targeted Herbicide Rover",
    guide_name: "Dr. T. Geetha",
    guide_designation: "Associate Professor",
    guide_department: "CSE",
    evaluation_stage: "Stage 1",
    session_label: "Official PRC Examination Session",
    students: ["Harish P", "Mythili R", "Kishore V", "Soundarya S"],
    submission_date: "25 Aug 2026",
    submission_time: "12:30",
    evaluation_date: "Wednesday, August 26, 2026",
    evaluation_time: "2:15 PM",
    marks_awarded: 87.5,
    max_marks: 100,
    status: "EVALUATED",
    feedback: "Computer vision bounding box precision on crop weeds verified.",
    criteria_scores: {
      project_execution: 17.5,
      technical_depth: 17.5,
      presentation_viva: 17.5,
      documentation: 17.5,
      contribution: 17.5,
    },
  },
  {
    id: "eval-rec-wed-3",
    advisor_id: "adv-4",
    advisor_name: "Dr. M. K. Raman",
    batch: "2025–2029",
    team_id: "team-grid",
    team_name: "Team SmartGrid",
    project_title: "Blockchain Enabled P2P Solar Energy Trading",
    guide_name: "Dr. R. Kavitha",
    guide_designation: "Associate Professor",
    guide_department: "CSE",
    evaluation_stage: "Stage 1",
    session_label: "Official PRC Examination Session",
    students: ["Srinath K", "Pavithra M", "Ganesh T", "Bhavani S"],
    submission_date: "25 Aug 2026",
    submission_time: "13:15",
    evaluation_date: "Wednesday, August 26, 2026",
    evaluation_time: "2:15 PM",
    marks_awarded: 97.5,
    max_marks: 100,
    status: "EVALUATED",
    feedback: "Exceptional smart contract auction matching algorithm.",
    criteria_scores: {
      project_execution: 19.5,
      technical_depth: 19.5,
      presentation_viva: 19.5,
      documentation: 19.5,
      contribution: 19.5,
    },
  },
  {
    id: "eval-rec-wed-4",
    advisor_id: "adv-4",
    advisor_name: "Dr. M. K. Raman",
    batch: "2025–2029",
    team_id: "team-secure",
    team_name: "Team SecurePass",
    project_title: "Biometric Keystroke Dynamics Authentication",
    guide_name: "Dr. R. Kavitha",
    guide_designation: "Associate Professor",
    guide_department: "CSE",
    evaluation_stage: "Stage 1",
    session_label: "Official PRC Examination Session",
    students: ["Vimal R", "Shreya N", "Dharun K", "Geethanjali P"],
    submission_date: "25 Aug 2026",
    submission_time: "14:00",
    evaluation_date: "Wednesday, August 26, 2026",
    evaluation_time: "2:15 PM",
    marks_awarded: 90,
    max_marks: 100,
    status: "EVALUATED",
    feedback: "High biometric entropy in typing rhythm feature vector.",
    criteria_scores: {
      project_execution: 18,
      technical_depth: 18,
      presentation_viva: 18,
      documentation: 18,
      contribution: 18,
    },
  },
  {
    id: "eval-rec-wed-5",
    advisor_id: "adv-3",
    advisor_name: "Prof. S. Suresh",
    batch: "2025–2029",
    team_id: "team-aero",
    team_name: "Team AeroSense",
    project_title: "UAV Airborne LiDAR for Precision Forest Canopy Mapping",
    guide_name: "Dr. M. Senthil Nathan",
    guide_designation: "Professor",
    guide_department: "CSE",
    evaluation_stage: "Stage 1",
    session_label: "Official PRC Examination Session",
    students: ["Mithun V", "Sahana R", "Deepak K", "Lavanya S"],
    submission_date: "25 Aug 2026",
    submission_time: "15:00",
    evaluation_date: "Wednesday, August 26, 2026",
    evaluation_time: "2:15 PM",
    marks_awarded: 80,
    max_marks: 100,
    status: "EVALUATED",
    feedback: "LiDAR point cloud filtering demonstrated good vegetative index.",
    criteria_scores: {
      project_execution: 16,
      technical_depth: 16,
      presentation_viva: 16,
      documentation: 16,
      contribution: 16,
    },
  },
];

export const mockAdminChanges: AssignmentChangeRecord[] = [
  {
    id: "chg-1",
    timestamp: "06 Sep 2026, 14:30",
    change_type: "GUIDE_REASSIGNMENT",
    team_name: "Team RoboTech",
    batch: "2025–2029",
    changed_by: {
      name: "Er. M. Balaji",
      email: "admin.academic@siet.ac.in",
      role: "Central Registrar & Academic Admin",
    },
    reason:
      "Dr. S. Ramesh placed on emergency medical leave; reallocated to Dr. P. Suresh per PRC institutional committee circular #PRC-2026-88.",
    before_state: {
      guide: "Dr. S. Ramesh, M.E., Ph.D. (Associate Professor)",
      advisor: "Prof. S. Suresh",
      members: ["Rohit V", "Sanjay S", "Swetha M", "Varun K"],
      details: "Original project allocation under Robotics & Automation division.",
    },
    after_state: {
      guide: "Dr. P. Suresh, M.E., Ph.D. (Professor)",
      advisor: "Prof. S. Suresh",
      members: ["Rohit V", "Sanjay S", "Swetha M", "Varun K"],
      details: "Reassigned to Dr. P. Suresh; project scope and hardware budget preserved.",
    },
  },
  {
    id: "chg-2",
    timestamp: "28 Aug 2026, 11:15",
    change_type: "STAGE_EXTENDED",
    team_name: "Team QuantumCipher",
    batch: "2025–2029",
    changed_by: {
      name: "Er. M. Balaji",
      email: "admin.academic@siet.ac.in",
      role: "Central Registrar & Academic Admin",
    },
    reason:
      "FPGA evaluation board delivery delayed by vendor customs clearance. 7-day milestone grace period sanctioned.",
    before_state: {
      details: "Stage 3 Deadline: 05 Sep 2026",
    },
    after_state: {
      details: "Stage 3 Deadline: 12 Sep 2026 (Extended +7 Days)",
    },
  },
  {
    id: "chg-3",
    timestamp: "18 Aug 2026, 09:40",
    change_type: "ADVISOR_REASSIGNMENT",
    team_name: "Team SmartGrid",
    batch: "2025–2029",
    changed_by: {
      name: "Er. M. Balaji",
      email: "admin.academic@siet.ac.in",
      role: "Central Registrar & Academic Admin",
    },
    reason:
      "Balancing advisor workload quota across CSE-A and CSE-B divisions.",
    before_state: {
      advisor: "Prof. S. Suresh",
      guide: "Dr. R. Kavitha",
    },
    after_state: {
      advisor: "Dr. M. K. Raman",
      guide: "Dr. R. Kavitha",
    },
  },
];

export const mockComplianceRecords: AdvisorComplianceRecord[] = [
  {
    id: "comp-1",
    advisor_id: "adv-1",
    advisor_name: "Dr. K. Senthil Kumar",
    designation: "Associate Professor",
    department: "Computer Science & Engineering",
    assigned_teams: 4,
    completed_evaluations: 4,
    pending_evaluations: 0,
    overdue_reviews: 0,
    avg_score_given: 88.5,
    status: "COMPLETED",
    teams_breakdown: [
      { team_id: "team-1", team_name: "Team Alpha", stage_number: 3, marks_awarded: 18.5, is_overdue: false, evaluated_date: "28 Aug 2026" },
      { team_id: "team-2", team_name: "Team Beta", stage_number: 3, marks_awarded: 17.0, is_overdue: false, evaluated_date: "28 Aug 2026" },
      { team_id: "team-3", team_name: "Team Gamma", stage_number: 3, marks_awarded: 19.0, is_overdue: false, evaluated_date: "28 Aug 2026" },
      { team_id: "team-4", team_name: "Team Delta", stage_number: 3, marks_awarded: 16.5, is_overdue: false, evaluated_date: "28 Aug 2026" },
    ],
  },
  {
    id: "comp-2",
    advisor_id: "adv-2",
    advisor_name: "Dr. A. Nandhini",
    designation: "Professor",
    department: "Electrical & Electronics Engineering",
    assigned_teams: 4,
    completed_evaluations: 2,
    pending_evaluations: 2,
    overdue_reviews: 0,
    avg_score_given: 91.2,
    status: "IN_PROGRESS",
    teams_breakdown: [
      { team_id: "team-neuro", team_name: "Team NeuroSync", stage_number: 3, marks_awarded: 19.0, is_overdue: false, evaluated_date: "05 Sep 2026" },
      { team_id: "team-solar", team_name: "Team SolarSense", stage_number: 3, marks_awarded: 17.5, is_overdue: false, evaluated_date: "05 Sep 2026" },
      { team_id: "team-qc", team_name: "Team QuantumCipher", stage_number: 3, is_overdue: false, submitted_date: "04 Sep 2026" },
      { team_id: "team-echo", team_name: "Team EchoGrid", stage_number: 3, is_overdue: false, submitted_date: "05 Sep 2026" },
    ],
  },
  {
    id: "comp-3",
    advisor_id: "adv-3",
    advisor_name: "Prof. S. Suresh",
    designation: "Assistant Professor (Sr. Grade)",
    department: "Computer Science & Engineering",
    assigned_teams: 4,
    completed_evaluations: 1,
    pending_evaluations: 3,
    overdue_reviews: 3,
    avg_score_given: 80.0,
    status: "OVERDUE",
    teams_breakdown: [
      { team_id: "team-aero", team_name: "Team AeroSense", stage_number: 3, marks_awarded: 16.0, is_overdue: false, evaluated_date: "20 Aug 2026" },
      { team_id: "team-vision", team_name: "Team VisionAI", stage_number: 3, is_overdue: true, submitted_date: "25 Aug 2026" },
      { team_id: "team-robo", team_name: "Team RoboTech", stage_number: 3, is_overdue: true, submitted_date: "26 Aug 2026" },
      { team_id: "team-cyber", team_name: "Team CyberShield", stage_number: 3, is_overdue: true, submitted_date: "26 Aug 2026" },
    ],
  },
  {
    id: "comp-4",
    advisor_id: "adv-4",
    advisor_name: "Dr. M. K. Raman",
    designation: "Associate Professor",
    department: "Computer Science & Engineering",
    assigned_teams: 4,
    completed_evaluations: 4,
    pending_evaluations: 0,
    overdue_reviews: 0,
    avg_score_given: 92.0,
    status: "COMPLETED",
    teams_breakdown: [
      { team_id: "team-med", team_name: "Team MedTech", stage_number: 3, marks_awarded: 18.0, is_overdue: false, evaluated_date: "02 Sep 2026" },
      { team_id: "team-agri", team_name: "Team AgroBot", stage_number: 3, marks_awarded: 17.5, is_overdue: false, evaluated_date: "02 Sep 2026" },
      { team_id: "team-grid", team_name: "Team SmartGrid", stage_number: 3, marks_awarded: 19.5, is_overdue: false, evaluated_date: "02 Sep 2026" },
      { team_id: "team-secure", team_name: "Team SecurePass", stage_number: 3, marks_awarded: 18.0, is_overdue: false, evaluated_date: "02 Sep 2026" },
    ],
  },
];

// ============================================================================
// HOD SERVICE API METHODS
// ============================================================================

export const hodService = {
  async getDashboardSummary(): Promise<HodDashboardSummary> {
    await new Promise((r) => setTimeout(r, 80));
    return mockDashboardSummary;
  },

  async getMilestoneStages(): Promise<HodMilestoneStage[]> {
    await new Promise((r) => setTimeout(r, 60));
    return mockMilestoneStages;
  },

  async getAttentionItems(): Promise<AttentionRequiredItem[]> {
    await new Promise((r) => setTimeout(r, 60));
    return mockAttentionItems;
  },

  async getLiveActivity(): Promise<LiveActivityEvent[]> {
    await new Promise((r) => setTimeout(r, 60));
    return mockLiveActivityStream;
  },

  async getAdvisors(batch?: string): Promise<HodAdvisorRecord[]> {
    await new Promise((r) => setTimeout(r, 100));
    if (!batch || batch === "All" || batch.includes("2025")) {
      return mockAdvisorsList;
    }
    return mockAdvisorsList.map((a) => ({
      ...a,
      batch: batch,
      teams_count: Math.max(2, a.teams_count - 1),
      students_count: Math.max(8, a.students_count - 4),
    }));
  },

  async getAdvisorById(id: string, batch?: string): Promise<HodAdvisorRecord | null> {
    await new Promise((r) => setTimeout(r, 60));
    const advisor = mockAdvisorsList.find((a) => a.id === id) || mockAdvisorsList[0];
    if (batch && advisor) {
      return { ...advisor, batch };
    }
    return advisor || null;
  },

  async getAdvisorEvaluationHistory(
    advisorId: string,
    batch?: string
  ): Promise<AdvisorEvaluationHistoryRecord[]> {
    await new Promise((r) => setTimeout(r, 80));
    const faculty = mockAdvisorsList.find((f) => f.id === advisorId);

    // Check if faculty has directly matching evaluation records
    let records = mockEvaluationHistoryRecords.filter(
      (rec) => rec.advisor_id === advisorId || advisorId === "all"
    );

    // If no advisor records match, check if faculty is a guide on records
    if (records.length === 0 && faculty) {
      const cleanName = faculty.name.replace(/Dr\.|Prof\./g, "").trim().toLowerCase();
      const guideMatches = mockEvaluationHistoryRecords.filter((rec) =>
        rec.guide_name.toLowerCase().includes(cleanName)
      );
      if (guideMatches.length > 0) {
        records = guideMatches;
      }
    }

    // Fallback: customize records for this faculty member so every advisor & guide displays full evaluation records
    if (records.length === 0) {
      records = mockEvaluationHistoryRecords.map((r) => ({
        ...r,
        advisor_id: advisorId,
        advisor_name: faculty?.role === "GUIDE" ? r.advisor_name : (faculty ? faculty.name : r.advisor_name),
        guide_name: faculty?.role === "GUIDE" ? faculty.name : r.guide_name,
      }));
    }

    if (batch) {
      return records.map((r) => ({ ...r, batch }));
    }
    return records;
  },

  async getAdminChangeHistory(): Promise<AssignmentChangeRecord[]> {
    await new Promise((r) => setTimeout(r, 80));
    return mockAdminChanges;
  },

  async getComplianceRecords(): Promise<AdvisorComplianceRecord[]> {
    await new Promise((r) => setTimeout(r, 80));
    return mockComplianceRecords;
  },
};
