$kind: http-request
url: "{{baseUrl}}/api/v1/admin/settings"
method: PATCH
headers:
  Accept: application/json
settings: {}
examples: ./.resources/Update portal settings.resources/examples
order: 2000
