"""Add supabase_uid to users

Revision ID: 7e07063eedca
Revises: '822f886e0c37'
Create Date: 2026-09-07 16:09:24.592660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e07063eedca'
down_revision: Union[str, None] = '822f886e0c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supabase_uid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_users_supabase_uid'), 'users', ['supabase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_supabase_uid'), table_name='users')
    op.drop_column('users', 'supabase_uid')
    # ### end Alembic commands ###
