"""Add github_url and live_demo_url to projects table

Revision ID: e5c635ecd1f0
Revises: 'a1b2c3d4e5f6'
Create Date: 2026-09-08 19:52:12.893992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c635ecd1f0'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('live_demo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'live_demo_url')
    op.drop_column('projects', 'github_url')
    # ### end Alembic commands ###
