import {
  StudentProfile,
  MyTeamResponse,
  ProjectResponse,
  MyFilesResponse,
  SubmissionChecklist,
  MySubmissionResponse,
  LoginResponse,
} from "@/types";

export const mockStudentUser: LoginResponse = {
  access_token: "demo_jwt_student_token_siet_autonomous",
  token_type: "bearer",
  user: {
    id: "student-uuid-demo-001",
    roll_number: "23CS001",
    full_name: "Rahul Sharma",
    email: "rahul.23cs@siet.ac.in",
    role: "student",
    team_id: "team-uuid-alpha-001",
  },
};

export const mockAdvisorUser: LoginResponse = {
  access_token: "demo_jwt_advisor_token_siet_autonomous",
  token_type: "bearer",
  user: {
    id: "advisor-uuid-demo-001",
    roll_number: null,
    full_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
    email: "senthilkumar.cse@siet.ac.in",
    role: "advisor",
    team_id: null,
  },
};

export const mockHodUser: LoginResponse = {
  access_token: "demo_jwt_hod_token_siet_autonomous",
  token_type: "bearer",
  user: {
    id: "hod-uuid-demo-001",
    roll_number: null,
    full_name: "Dr. A. Murugesan, M.E., Ph.D.",
    email: "hod.cse@siet.ac.in",
    role: "hod",
    team_id: null,
  },
};

export const mockStudentProfile: StudentProfile = {
  id: "student-uuid-demo-001",
  roll_number: "23CS001",
  full_name: "Rahul Sharma",
  email: "rahul.23cs@siet.ac.in",
  role: "student",
  team_id: "team-uuid-alpha-001",
};

export const mockTeam: MyTeamResponse = {
  team_id: "team-uuid-alpha-001",
  name: "Team Alpha (CSE-A)",
  project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
  batch: "2023-2027",
  section: "A",
  team_leader: {
    id: "student-uuid-demo-001",
    roll_number: "23CS001",
    full_name: "Rahul Sharma",
    is_team_leader: true,
  },
  members: [
    {
      id: "student-uuid-demo-001",
      roll_number: "23CS001",
      full_name: "Rahul Sharma",
      is_team_leader: true,
      email: "rahul.23cs@siet.ac.in",
    },
    {
      id: "student-uuid-demo-002",
      roll_number: "23CS014",
      full_name: "Priya Dharshini",
      is_team_leader: false,
      email: "priya.23cs@siet.ac.in",
    },
    {
      id: "student-uuid-demo-003",
      roll_number: "23CS028",
      full_name: "Karthik Raja",
      is_team_leader: false,
      email: "karthik.23cs@siet.ac.in",
    },
    {
      id: "student-uuid-demo-004",
      roll_number: "23CS042",
      full_name: "Ananya Iyer",
      is_team_leader: false,
      email: "ananya.23cs@siet.ac.in",
    },
  ],
  advisor: {
    id: "advisor-uuid-demo-001",
    full_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
    email: "senthilkumar.cse@siet.ac.in",
  },
};

export const mockProject: ProjectResponse = {
  id: "proj-uuid-demo-001",
  team_id: "team-uuid-alpha-001",
  title: "AI-Powered Smart Attendance & Campus Surveillance System",
  domain: "Artificial Intelligence & Edge Computing",
  problem_statement:
    "Manual attendance logging in large autonomous universities causes an average 12-minute delay per lecture block and suffers from proxy entries. Traditional biometric scanners also cause physical bottlenecks during morning peak arrivals.",
  description:
    "An edge-computing computer vision platform that performs multi-camera facial recognition and tracking across university entrance portals and lecture halls, synchronizing verified student arrivals directly to the autonomous ERP in real-time.",
  proposed_solution:
    "Deploying lightweight YOLOv11 + FaceNet embedding extraction models optimized via ONNX Runtime on edge Jetson nodes. Cryptographic HMAC timestamps prevent spoofing, and automated alerts report unauthorized campus entries to administrative security.",
  technologies_used:
    "Python, FastAPI, PyTorch, YOLOv11, Next.js, PostgreSQL, Docker, Redis",
  github_url: "https://github.com/siet-autonomous/ai-smart-attendance",
  live_demo_url: "https://attendance.siet-demo.ac.in",
};

export const mockFiles: MyFilesResponse = {
  count: 3,
  files: [
    {
      id: "file-uuid-001",
      project_id: "proj-uuid-demo-001",
      team_id: "team-uuid-alpha-001",
      category: "ABSTRACT",
      original_filename: "SIET_PRC_Abstract_TeamAlpha_v2.pdf",
      storage_path: "teams/team-alpha/abstract.pdf",
      mime_type: "application/pdf",
      file_size: 1450230,
      created_at: "2026-08-28T10:30:00Z",
      updated_at: "2026-08-28T10:30:00Z",
    },
    {
      id: "file-uuid-002",
      project_id: "proj-uuid-demo-001",
      team_id: "team-uuid-alpha-001",
      category: "REPORT",
      original_filename: "TeamAlpha_Project_Report_Final_IEEE.pdf",
      storage_path: "teams/team-alpha/report.pdf",
      mime_type: "application/pdf",
      file_size: 4892300,
      created_at: "2026-09-01T14:15:00Z",
      updated_at: "2026-09-01T14:15:00Z",
    },
    {
      id: "file-uuid-003",
      project_id: "proj-uuid-demo-001",
      team_id: "team-uuid-alpha-001",
      category: "PPT",
      original_filename: "TeamAlpha_VivaVoce_Presentation_Deck.pptx",
      storage_path: "teams/team-alpha/presentation.pptx",
      mime_type: "application/vnd.ms-powerpoint",
      file_size: 6120400,
      created_at: "2026-09-02T09:45:00Z",
      updated_at: "2026-09-02T09:45:00Z",
    },
  ],
};

export const mockChecklist: SubmissionChecklist = {
  abstract: { completed: true, label: "Abstract Document (PDF)" },
  report: { completed: true, label: "Comprehensive Project Report (PDF)" },
  ppt: { completed: true, label: "Presentation Slide Deck (PPT)" },
  images: { completed: true, label: "Project Architecture & Screenshots" },
  github: { completed: true, label: "GitHub Repository VCS Link" },
  live_demo: { completed: true, label: "Live Deployment / Video URL" },
  completed_count: 6,
  total_count: 6,
  all_completed: true,
};

export const mockSubmission: MySubmissionResponse = {
  submission_id: "sub-uuid-demo-001",
  status: "SUBMITTED",
  submitted_at: "2026-09-02T16:20:00Z",
  checklist: mockChecklist,
  files: mockFiles.files,
  project: mockProject,
};

export const mockWeeklySubmissionHistory: import("@/types").WeeklySubmissionHistoryResponse = {
  project_info: {
    project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
    domain: "Artificial Intelligence & Edge Computing",
    team_id: "team-uuid-alpha-001",
    team_name: "Team Alpha (CSE-A)",
    guide_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
    guide_email: "senthilkumar.cse@siet.ac.in",
    student_roll: "23CS001",
    student_name: "Rahul Sharma",
    problem_statement:
      "Manual attendance logging in large autonomous universities causes an average 12-minute delay per lecture block and suffers from proxy entries. Traditional biometric scanners also cause physical bottlenecks during morning peak arrivals.",
    description:
      "An edge-computing computer vision platform that performs multi-camera facial recognition and tracking across university entrance portals and lecture halls, synchronizing verified student arrivals directly to the autonomous ERP in real-time.",
    proposed_solution:
      "Deploying lightweight YOLOv11 + FaceNet embedding extraction models optimized via ONNX Runtime on edge Jetson nodes. Cryptographic HMAC timestamps prevent spoofing, and automated alerts report unauthorized campus entries to administrative security.",
    technologies_used:
      "Python, FastAPI, PyTorch, YOLOv11, Next.js, PostgreSQL, Docker, Redis",
  },
  summary: {
    total_weeks: 4,
    approved_count: 3,
    rejected_count: 1,
    pending_count: 1,
    current_progress_percentage: 72,
    submission_rate_percentage: 100,
    on_time_count: 3,
    total_submitted_count: 4,
  },
  current_week: {
    id: "sub-week-04",
    week_number: 4,
    week_title: "Week 4: Edge Deployment & Live Video Pipeline",
    is_current_week: true,
    submission_date: "Monday, 07 Sep 2026",
    submission_time: "09:45 AM",
    deadline: "Monday, 07 Sep 2026, 11:59 PM",
    deadline_timestamp: "2026-09-07T23:59:59Z",
    is_late: false,
    status: "UNDER_REVIEW",
    submission_type: "Weekly Phase I Milestone Submission",
    guide_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
    guide_designation: "Associate Professor / PRC Faculty Advisor",
    guide_email: "senthilkumar.cse@siet.ac.in",
    progress_contribution: 12,
    guide_remarks:
      "Draft submission registered. Pre-deadline modification and resubmission window is active.",
    is_locked: false,
    is_evaluated: false,
    auto_submitted: false,
    github_url: "https://github.com/siet-autonomous/ai-smart-attendance",
    live_demo_url: "https://attendance.siet-demo.ac.in",
    problems_faced:
      "Encountered memory bandwidth bottlenecks while running batch inferences with FP16 precision on Jetson Orin Nano. Resolved by compiling models with TensorRT execution provider.",
    next_week_plan:
      "Finalize multi-camera re-identification (ReID) module and benchmark false acceptance rate (FAR) across low-light illumination conditions.",
    files: [
      {
        name: "SIET_PRC_Phase1_Edge_Benchmark_Report.pdf",
        category: "REPORT",
        size: 3840200,
        upload_date: "04 Sep 2026, 09:30 PM",
        status: "UPLOADED",
        url: "#",
      },
      {
        name: "Jetson_Deployment_Pipeline_Slides.pptx",
        category: "PPT",
        size: 5120800,
        upload_date: "05 Sep 2026, 07:45 AM",
        status: "UPLOADED",
        url: "#",
      },
    ],
    attempts: [
      {
        attempt_number: 1,
        submitted_at: "05 Sep 2026, 08:12 AM",
        submission_time: "Saturday, 08:12 AM",
        status: "UNDER_REVIEW",
        is_late: false,
        deadline: "Saturday, 08:30 AM",
        guide_remarks: "Under review by Project Review Committee.",
        files: [
          {
            name: "SIET_PRC_Phase1_Edge_Benchmark_Report.pdf",
            category: "REPORT",
            size: 3840200,
            upload_date: "04 Sep 2026, 09:30 PM",
            status: "UPLOADED",
          },
        ],
        problems_faced:
          "Encountered memory bandwidth bottlenecks on Jetson Orin Nano.",
        next_week_plan: "Complete ReID module across outdoor entry portals.",
        timeline: [
          {
            title: "Submission Created",
            timestamp: "Monday, 31 Aug 2026, 09:10 AM",
            status: "done",
          },
          {
            title: "Files Uploaded",
            timestamp: "Friday, 04 Sep 2026, 09:30 PM",
            status: "done",
          },
          {
            title: "Submitted On Time",
            timestamp: "Saturday, 05 Sep 2026, 08:12 AM",
            status: "done",
          },
          {
            title: "Under PRC Guide Review",
            timestamp: "Saturday, 05 Sep 2026, 08:45 AM",
            status: "current",
          },
        ],
      },
    ],
    timeline: [
      {
        title: "Submission Created",
        timestamp: "Monday, 31 Aug 2026, 09:10 AM",
        status: "done",
      },
      {
        title: "Deliverables Uploaded",
        timestamp: "Friday, 04 Sep 2026, 09:30 PM",
        status: "done",
      },
      {
        title: "Submitted On Time",
        timestamp: "Saturday, 05 Sep 2026, 08:12 AM",
        status: "done",
      },
      {
        title: "Under PRC Guide Review",
        timestamp: "Saturday, 05 Sep 2026, 08:45 AM",
        status: "current",
      },
    ],
  },
  submissions: [
    {
      id: "sub-week-01",
      week_number: 1,
      week_title: "Week 1: Problem Formulation & Architecture Design",
      is_current_week: false,
      submission_date: "Saturday, 15 Aug 2026",
      submission_time: "08:15 AM",
      deadline: "Saturday, 15 Aug 2026, 08:30 AM",
      deadline_timestamp: "2026-08-15T08:30:00Z",
      is_late: false,
      status: "APPROVED",
      submission_type: "Weekly Phase Milestone Submission",
      guide_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
      guide_designation: "Associate Professor / PRC Faculty Advisor",
      guide_email: "senthilkumar.cse@siet.ac.in",
      progress_contribution: 18,
      guide_remarks:
        "Thorough literature review and clearly formulated problem statement. Architecture diagrams meet IEEE standard formatting.",
      reviewed_at: "Saturday, 15 Aug 2026, 11:45 AM",
      is_locked: true,
      is_evaluated: true,
      marks_awarded: 94,
      max_marks: 100,
      grade: "A+",
      evaluated_by: "Dr. K. Senthil Kumar, M.E., Ph.D.",
      evaluated_at: "Saturday, 15 Aug 2026, 11:45 AM",
      criteria_scores: {
        "Problem Definition & Scope": { score: 19, max: 20 },
        "Literature Survey & Feasibility": { score: 19, max: 20 },
        "System Architecture & Dataflow": { score: 19, max: 20 },
        "Documentation & IEEE Format": { score: 18, max: 20 },
        "Viva Voce & Technical Defense": { score: 19, max: 20 },
      },
      auto_submitted: false,
      github_url: "https://github.com/siet-autonomous/ai-smart-attendance",
      live_demo_url: "",
      problems_faced:
        "Selecting appropriate neural network backbone suitable for low-power edge nodes.",
      next_week_plan:
        "Build the synthetic video dataset pipeline and camera stream RTSP ingest service.",
      files: [
        {
          name: "SIET_PRC_Abstract_TeamAlpha_v1.pdf",
          category: "ABSTRACT",
          size: 1450230,
          upload_date: "14 Aug 2026, 06:15 PM",
          status: "APPROVED",
          url: "#",
        },
        {
          name: "Architecture_System_Design_Block_Diagram.png",
          category: "IMAGE",
          size: 2100450,
          upload_date: "14 Aug 2026, 08:20 PM",
          status: "APPROVED",
          url: "#",
        },
      ],
      attempts: [
        {
          attempt_number: 1,
          submitted_at: "15 Aug 2026, 08:15 AM",
          submission_time: "Saturday, 08:15 AM",
          status: "APPROVED",
          is_late: false,
          deadline: "Saturday, 08:30 AM",
          guide_remarks:
            "Thorough literature review and clearly formulated problem statement. Architecture diagrams meet IEEE standard formatting.",
          reviewed_at: "15 Aug 2026, 11:45 AM",
          reviewed_by: "Dr. K. Senthil Kumar",
          files: [
            {
              name: "SIET_PRC_Abstract_TeamAlpha_v1.pdf",
              category: "ABSTRACT",
              size: 1450230,
              upload_date: "14 Aug 2026, 06:15 PM",
              status: "APPROVED",
            },
          ],
          problems_faced:
            "Selecting neural network backbone for low-power edge nodes.",
          next_week_plan: "Build dataset pipeline and RTSP ingest service.",
          timeline: [
            {
              title: "Submission Created",
              timestamp: "Monday, 10 Aug 2026, 09:10 AM",
              status: "done",
            },
            {
              title: "Files Uploaded",
              timestamp: "Friday, 14 Aug 2026, 06:25 PM",
              status: "done",
            },
            {
              title: "Submitted",
              timestamp: "Saturday, 15 Aug 2026, 08:15 AM",
              status: "done",
            },
            {
              title: "Guide Review",
              timestamp: "Saturday, 15 Aug 2026, 11:30 AM",
              status: "done",
            },
            {
              title: "Approved",
              timestamp: "Saturday, 15 Aug 2026, 11:45 AM",
              status: "done",
            },
            {
              title: "Progress Updated (+18%)",
              timestamp: "Saturday, 15 Aug 2026, 11:46 AM",
              status: "done",
            },
          ],
        },
      ],
      timeline: [
        {
          title: "Submission Created",
          timestamp: "Monday, 10 Aug 2026, 09:10 AM",
          status: "done",
        },
        {
          title: "Files Uploaded",
          timestamp: "Friday, 14 Aug 2026, 06:25 PM",
          status: "done",
        },
        {
          title: "Submitted",
          timestamp: "Saturday, 15 Aug 2026, 08:15 AM",
          status: "done",
        },
        {
          title: "Guide Review",
          timestamp: "Saturday, 15 Aug 2026, 11:30 AM",
          status: "done",
        },
        {
          title: "Approved",
          timestamp: "Saturday, 15 Aug 2026, 11:45 AM",
          status: "done",
        },
        {
          title: "Progress Updated (+18%)",
          timestamp: "Saturday, 15 Aug 2026, 11:46 AM",
          status: "done",
        },
      ],
    },
    {
      id: "sub-week-02",
      week_number: 2,
      week_title: "Week 2: Dataset Pipeline & Preprocessing Module",
      is_current_week: false,
      submission_date: "Saturday, 22 Aug 2026",
      submission_time: "08:22 AM",
      deadline: "Saturday, 22 Aug 2026, 08:30 AM",
      deadline_timestamp: "2026-08-22T08:30:00Z",
      is_late: false,
      status: "APPROVED",
      submission_type: "Weekly Phase Milestone Submission",
      guide_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
      guide_designation: "Associate Professor / PRC Faculty Advisor",
      guide_email: "senthilkumar.cse@siet.ac.in",
      progress_contribution: 20,
      guide_remarks:
        "Dataset curation is comprehensive. Image augmentation pipelines and institutional privacy compliance verified.",
      reviewed_at: "Saturday, 22 Aug 2026, 01:10 PM",
      is_locked: true,
      is_evaluated: true,
      marks_awarded: 91,
      max_marks: 100,
      grade: "A",
      evaluated_by: "Dr. K. Senthil Kumar, M.E., Ph.D.",
      evaluated_at: "Saturday, 22 Aug 2026, 01:10 PM",
      criteria_scores: {
        "Dataset Curation & Privacy Compliance": { score: 18, max: 20 },
        "Image Augmentation Pipeline": { score: 19, max: 20 },
        "Preprocessing Module Architecture": { score: 18, max: 20 },
        "Code Repository Hygiene": { score: 18, max: 20 },
        "Guide Clarifications & Defense": { score: 18, max: 20 },
      },
      auto_submitted: false,
      github_url: "https://github.com/siet-autonomous/ai-smart-attendance",
      live_demo_url: "",
      problems_faced:
        "Managing class imbalance across different lecture hall lighting setups.",
      next_week_plan:
        "Train and optimize YOLOv11 + FaceNet facial detection models.",
      files: [
        {
          name: "TeamAlpha_Dataset_Preprocessing_Report.pdf",
          category: "REPORT",
          size: 2980120,
          upload_date: "21 Aug 2026, 11:10 PM",
          status: "APPROVED",
          url: "#",
        },
        {
          name: "Data_Augmentation_Techniques_Review2.pptx",
          category: "PPT",
          size: 4320900,
          upload_date: "22 Aug 2026, 07:15 AM",
          status: "APPROVED",
          url: "#",
        },
      ],
      attempts: [
        {
          attempt_number: 1,
          submitted_at: "22 Aug 2026, 08:22 AM",
          submission_time: "Saturday, 08:22 AM",
          status: "APPROVED",
          is_late: false,
          deadline: "Saturday, 08:30 AM",
          guide_remarks:
            "Dataset curation is comprehensive. Image augmentation pipelines and institutional privacy compliance verified.",
          reviewed_at: "22 Aug 2026, 01:10 PM",
          reviewed_by: "Dr. K. Senthil Kumar",
          files: [
            {
              name: "TeamAlpha_Dataset_Preprocessing_Report.pdf",
              category: "REPORT",
              size: 2980120,
              upload_date: "21 Aug 2026, 11:10 PM",
              status: "APPROVED",
            },
          ],
          problems_faced: "Managing class imbalance across lighting setups.",
          next_week_plan: "Train and optimize YOLOv11 + FaceNet models.",
          timeline: [
            {
              title: "Submission Created",
              timestamp: "Monday, 17 Aug 2026, 09:30 AM",
              status: "done",
            },
            {
              title: "Files Uploaded",
              timestamp: "Friday, 21 Aug 2026, 11:10 PM",
              status: "done",
            },
            {
              title: "Submitted On Time",
              timestamp: "Saturday, 22 Aug 2026, 08:22 AM",
              status: "done",
            },
            {
              title: "Guide Review",
              timestamp: "Saturday, 22 Aug 2026, 01:00 PM",
              status: "done",
            },
            {
              title: "Approved",
              timestamp: "Saturday, 22 Aug 2026, 01:10 PM",
              status: "done",
            },
            {
              title: "Progress Updated (+20%)",
              timestamp: "Saturday, 22 Aug 2026, 01:12 PM",
              status: "done",
            },
          ],
        },
      ],
      timeline: [
        {
          title: "Submission Created",
          timestamp: "Monday, 17 Aug 2026, 09:30 AM",
          status: "done",
        },
        {
          title: "Files Uploaded",
          timestamp: "Friday, 21 Aug 2026, 11:10 PM",
          status: "done",
        },
        {
          title: "Submitted On Time",
          timestamp: "Saturday, 22 Aug 2026, 08:22 AM",
          status: "done",
        },
        {
          title: "Guide Review",
          timestamp: "Saturday, 22 Aug 2026, 01:00 PM",
          status: "done",
        },
        {
          title: "Approved",
          timestamp: "Saturday, 22 Aug 2026, 01:10 PM",
          status: "done",
        },
        {
          title: "Progress Updated (+20%)",
          timestamp: "Saturday, 22 Aug 2026, 01:12 PM",
          status: "done",
        },
      ],
    },
    {
      id: "sub-week-03",
      week_number: 3,
      week_title: "Week 3: Neural Model Training & Benchmarking",
      is_current_week: false,
      submission_date: "Saturday, 29 Aug 2026",
      submission_time: "04:20 PM",
      deadline: "Saturday, 29 Aug 2026, 08:30 AM",
      deadline_timestamp: "2026-08-29T08:30:00Z",
      is_late: false,
      status: "APPROVED",
      submission_type: "Weekly Phase Milestone Submission",
      guide_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
      guide_designation: "Associate Professor / PRC Faculty Advisor",
      guide_email: "senthilkumar.cse@siet.ac.in",
      progress_contribution: 22,
      guide_remarks:
        "Corrections completed satisfactorily. Added comprehensive precision-recall metrics and ablation tables for FaceNet embedding dimensions.",
      rejection_reason:
        "Attempt 1 rejected due to missing YOLOv11 benchmark comparison and absence of loss convergence curves.",
      reviewed_at: "Saturday, 29 Aug 2026, 05:40 PM",
      is_locked: true,
      is_evaluated: true,
      marks_awarded: 88,
      max_marks: 100,
      grade: "B+",
      evaluated_by: "Dr. K. Senthil Kumar, M.E., Ph.D.",
      evaluated_at: "Saturday, 29 Aug 2026, 05:40 PM",
      criteria_scores: {
        "Neural Model Training & Loss Convergence": { score: 18, max: 20 },
        "Precision-Recall & Benchmarking": { score: 17, max: 20 },
        "Hardware Latency Optimization": { score: 18, max: 20 },
        "Correction of Review Comments": { score: 18, max: 20 },
        "Technical Presentation": { score: 17, max: 20 },
      },
      auto_submitted: false,
      github_url: "https://github.com/siet-autonomous/ai-smart-attendance",
      live_demo_url: "https://attendance.siet-demo.ac.in",
      problems_faced:
        "Initially omitted comparative latency benchmarks between CPU and TensorRT engines.",
      next_week_plan:
        "Deploy model on Jetson edge device and connect with university RTSP camera streams.",
      files: [
        {
          name: "TeamAlpha_Model_Training_Report_v2_Corrected.pdf",
          category: "REPORT",
          size: 4210500,
          upload_date: "29 Aug 2026, 03:55 PM",
          status: "APPROVED",
          url: "#",
        },
        {
          name: "Loss_Curves_And_mAP_Comparison.png",
          category: "IMAGE",
          size: 1850300,
          upload_date: "29 Aug 2026, 04:05 PM",
          status: "APPROVED",
          url: "#",
        },
      ],
      attempts: [
        {
          attempt_number: 1,
          submitted_at: "29 Aug 2026, 08:10 AM",
          submission_time: "Saturday, 08:10 AM",
          status: "REJECTED",
          is_late: false,
          deadline: "Saturday, 08:30 AM",
          guide_remarks:
            "Report requires correction. Benchmark comparison with existing state-of-the-art models is missing. Loss curves not provided.",
          rejection_reason:
            "Incomplete benchmarking metrics and missing model ablation study.",
          reviewed_at: "29 Aug 2026, 11:30 AM",
          reviewed_by: "Dr. K. Senthil Kumar",
          files: [
            {
              name: "TeamAlpha_Model_Training_Report_v1.pdf",
              category: "REPORT",
              size: 3410200,
              upload_date: "28 Aug 2026, 10:30 PM",
              status: "REJECTED",
            },
          ],
          problems_faced: "Omitted comparative latency benchmarks.",
          next_week_plan: "Complete model training.",
          timeline: [
            {
              title: "Submission Created",
              timestamp: "Monday, 24 Aug 2026, 09:10 AM",
              status: "done",
            },
            {
              title: "Submitted",
              timestamp: "Saturday, 29 Aug 2026, 08:10 AM",
              status: "done",
            },
            {
              title: "Guide Review",
              timestamp: "Saturday, 29 Aug 2026, 11:15 AM",
              status: "done",
            },
            {
              title: "Rejected by Guide",
              timestamp: "Saturday, 29 Aug 2026, 11:30 AM",
              description: "Reason: Benchmark comparison with YOLOv11 missing.",
              status: "rejected",
            },
          ],
        },
        {
          attempt_number: 2,
          submitted_at: "29 Aug 2026, 04:20 PM",
          submission_time: "Saturday, 04:20 PM",
          status: "APPROVED",
          is_late: false,
          deadline: "Resubmission Allowed: Saturday, 06:00 PM",
          guide_remarks:
            "Corrections completed. Detailed ablation tables and loss graphs successfully verified.",
          reviewed_at: "29 Aug 2026, 05:40 PM",
          reviewed_by: "Dr. K. Senthil Kumar",
          files: [
            {
              name: "TeamAlpha_Model_Training_Report_v2_Corrected.pdf",
              category: "REPORT",
              size: 4210500,
              upload_date: "29 Aug 2026, 03:55 PM",
              status: "APPROVED",
            },
          ],
          problems_faced: "Re-calculated all latency benchmarks on hardware.",
          next_week_plan: "Deploy model on Jetson edge node.",
          timeline: [
            {
              title: "Student Resubmitted",
              timestamp: "Saturday, 29 Aug 2026, 04:20 PM",
              status: "done",
            },
            {
              title: "Guide Review",
              timestamp: "Saturday, 29 Aug 2026, 05:30 PM",
              status: "done",
            },
            {
              title: "Approved",
              timestamp: "Saturday, 29 Aug 2026, 05:40 PM",
              status: "done",
            },
            {
              title: "Progress Updated (+22%)",
              timestamp: "Saturday, 29 Aug 2026, 05:42 PM",
              status: "done",
            },
          ],
        },
      ],
      timeline: [
        {
          title: "Submission Created",
          timestamp: "Monday, 24 Aug 2026, 09:10 AM",
          status: "done",
        },
        {
          title: "Initial Submission",
          timestamp: "Saturday, 29 Aug 2026, 08:10 AM",
          status: "done",
        },
        {
          title: "Guide Review",
          timestamp: "Saturday, 29 Aug 2026, 11:15 AM",
          status: "done",
        },
        {
          title: "Rejected by Guide",
          timestamp: "Saturday, 29 Aug 2026, 11:30 AM",
          description: "Reason: Benchmark comparison with YOLOv11 missing.",
          status: "rejected",
        },
        {
          title: "Student Resubmitted (Attempt 2)",
          timestamp: "Saturday, 29 Aug 2026, 04:20 PM",
          status: "done",
        },
        {
          title: "Guide Review",
          timestamp: "Saturday, 29 Aug 2026, 05:30 PM",
          status: "done",
        },
        {
          title: "Approved",
          timestamp: "Saturday, 29 Aug 2026, 05:40 PM",
          status: "done",
        },
        {
          title: "Progress Updated (+22%)",
          timestamp: "Saturday, 29 Aug 2026, 05:42 PM",
          status: "done",
        },
      ],
    },
  ],
};

// 7. Faculty / Advisor Portal Mock Data
export const mockAdvisorProfile: import("@/types").AdvisorProfile = {
  id: "advisor-uuid-demo-001",
  full_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
  email: "senthilkumar.cse@siet.ac.in",
  role: "advisor",
  department: "Department of Computer Science & Engineering",
  designation: "Associate Professor & PRC Faculty Advisor",
};

export const mockAdvisorTeams: import("@/types").AdvisorTeamSummary[] = [
  {
    id: "team-uuid-alpha-001",
    team_id: "team-uuid-alpha-001",
    name: "Team Alpha (CSE-A)",
    project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
    batch: "Batch 2023-27",
    section: "Sec A",
    department: "Computer Science & Engineering",
    current_phase: "Phase II / Final Review",
    submission_date: "04 Sep 2026, 09:30 PM",
    submission_status: "SUBMITTED",
    evaluation_status: "EVALUATED",
    evaluation_score: 92,
    marks_awarded: 92,
    grade: "A+",
    leader_name: "Rahul Sharma",
    leader_roll: "23CS001",
    evaluated_at: "Saturday, August 29, 2026 at 3:30 PM",
    evaluated_by: "Dr. K. Senthil Kumar, M.E., Ph.D.",
    evaluation_remarks: "Exceptional system design and live model inference benchmarks on Jetson hardware. IEEE standard formatting adhered to strictly.",
    members: [
      { id: "s1", full_name: "Rahul Sharma", roll_number: "23CS001", role: "AI Engineer & Team Leader", email: "rahul.23cs@siet.ac.in" },
      { id: "s2", full_name: "Priya Sundaram", roll_number: "23CS002", role: "Computer Vision Specialist", email: "priya.23cs@siet.ac.in" },
      { id: "s3", full_name: "Karthik Raja", roll_number: "23CS003", role: "Edge Computing & IoT Engineer", email: "karthik.23cs@siet.ac.in" },
      { id: "s4", full_name: "Ananya Krishnan", roll_number: "23CS004", role: "Full-Stack ERP Integrator", email: "ananya.23cs@siet.ac.in" },
    ],
    guide: {
      id: "advisor-uuid-demo-001",
      full_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
      email: "senthilkumar.cse@siet.ac.in",
      designation: "Associate Professor",
      department: "CSE",
    },
    evaluation: {
      id: "eval-01",
      team_id: "team-uuid-alpha-001",
      team_score: 92,
      team_remarks: "Exceptional system design and live model inference benchmarks on Jetson hardware. IEEE standard formatting adhered to strictly.",
      status: "EVALUATED",
      recommendation_status: "APPROVED",
      strengths: "High FPS edge inference with TensorRT quantization, clean modular architecture, and excellent viva presentation.",
      areas_for_improvement: "Include real-time latency jitter charts under low-bandwidth RTSP streaming.",
      criteria_scores: {
        project_execution: 19,
        technical_depth: 18.5,
        presentation_viva: 18,
        documentation: 18.5,
        contribution: 18,
      },
      evaluated_at: "Saturday, August 29, 2026 at 3:30 PM",
      evaluated_by: "Dr. K. Senthil Kumar, M.E., Ph.D.",
    },
  },
  {
    id: "team-uuid-beta-002",
    team_id: "team-uuid-beta-002",
    name: "Team Beta (CSE-B)",
    project_title: "Blockchain-Based Decentralized Credential Verification System",
    batch: "Batch 2023-27",
    section: "Sec B",
    department: "Computer Science & Engineering",
    current_phase: "Phase II / Final Review",
    submission_date: "03 Sep 2026, 05:15 PM",
    submission_status: "SUBMITTED",
    evaluation_status: "EVALUATED",
    evaluation_score: 88,
    marks_awarded: 88,
    grade: "A",
    leader_name: "Vigneshwaran K",
    leader_roll: "23CS045",
    evaluated_at: "Saturday, August 29, 2026 at 4:15 PM",
    evaluated_by: "Dr. K. Senthil Kumar, M.E., Ph.D.",
    evaluation_remarks: "Robust Solidity contract verification on Polygon testnet. Gas consumption benchmarks provided.",
    members: [
      { id: "s5", full_name: "Vigneshwaran K", roll_number: "23CS045", role: "Smart Contract Architect", email: "vignesh.23cs@siet.ac.in" },
      { id: "s6", full_name: "Sneha R", roll_number: "23CS046", role: "Frontend Web3 Developer", email: "sneha.23cs@siet.ac.in" },
      { id: "s7", full_name: "Deepak Kumar", roll_number: "23CS047", role: "Zero-Knowledge Proof Engineer", email: "deepak.23cs@siet.ac.in" },
      { id: "s8", full_name: "Lavanya M", roll_number: "23CS048", role: "Technical Documentation Lead", email: "lavanya.23cs@siet.ac.in" },
    ],
    guide: {
      id: "advisor-uuid-demo-001",
      full_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
      email: "senthilkumar.cse@siet.ac.in",
      designation: "Associate Professor",
      department: "CSE",
    },
    evaluation: {
      id: "eval-02",
      team_id: "team-uuid-beta-002",
      team_score: 88,
      team_remarks: "Robust Solidity contract verification on Polygon testnet. Gas consumption benchmarks provided.",
      status: "EVALUATED",
      recommendation_status: "APPROVED",
      strengths: "EVM compatibility, IPFS document storage, clean cryptographic verification.",
      areas_for_improvement: "Expand test coverage with Foundry fuzz testing.",
      criteria_scores: {
        project_execution: 18,
        technical_depth: 17.5,
        presentation_viva: 17.5,
        documentation: 18,
        contribution: 17,
      },
      evaluated_at: "Saturday, August 29, 2026 at 4:15 PM",
      evaluated_by: "Dr. K. Senthil Kumar, M.E., Ph.D.",
    },
  },
  {
    id: "team-uuid-gamma-003",
    team_id: "team-uuid-gamma-003",
    name: "Team Gamma (CSE-A)",
    project_title: "Automated Diabetic Retinopathy Screening via Multi-Modal Vision Transformer",
    batch: "Batch 2023-27",
    section: "Sec A",
    department: "Computer Science & Engineering",
    current_phase: "Phase II / Final Review",
    submission_date: "05 Sep 2026, 08:20 AM",
    submission_status: "SUBMITTED",
    evaluation_status: "PENDING",
    marks_awarded: undefined,
    leader_name: "Gowtham S",
    leader_roll: "23CS012",
    members: [
      { id: "s9", full_name: "Gowtham S", roll_number: "23CS012", role: "Medical AI Lead", email: "gowtham.23cs@siet.ac.in" },
      { id: "s10", full_name: "Keerthana V", roll_number: "23CS013", role: "Data Preprocessing & Augmentation", email: "keerthana.23cs@siet.ac.in" },
      { id: "s11", full_name: "Manoj P", roll_number: "23CS014", role: "Backend Ingest API", email: "manoj.23cs@siet.ac.in" },
      { id: "s12", full_name: "Divya N", roll_number: "23CS015", role: "UI/UX Clinical Dashboard", email: "divya.23cs@siet.ac.in" },
    ],
    guide: {
      id: "advisor-uuid-demo-001",
      full_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
      email: "senthilkumar.cse@siet.ac.in",
      designation: "Associate Professor",
      department: "CSE",
    },
  },
  {
    id: "team-uuid-delta-004",
    team_id: "team-uuid-delta-004",
    name: "Team Delta (CSE-C)",
    project_title: "Autonomous Drone Swarm Navigation in GPS-Denied Environments",
    batch: "Batch 2023-27",
    section: "Sec C",
    department: "Computer Science & Engineering",
    current_phase: "Phase I Review",
    submission_date: "05 Sep 2026, 10:45 AM",
    submission_status: "SUBMITTED",
    evaluation_status: "PENDING",
    marks_awarded: undefined,
    leader_name: "Siddharth B",
    leader_roll: "23CS089",
    members: [
      { id: "s13", full_name: "Siddharth B", roll_number: "23CS089", role: "SLAM & Odometry Specialist", email: "siddharth.23cs@siet.ac.in" },
      { id: "s14", full_name: "Meera T", roll_number: "23CS090", role: "PX4 Firmware & Hardware", email: "meera.23cs@siet.ac.in" },
      { id: "s15", full_name: "Ashwin K", roll_number: "23CS091", role: "Mesh Communications Lead", email: "ashwin.23cs@siet.ac.in" },
      { id: "s16", full_name: "Pavithra S", roll_number: "23CS092", role: "Simulation & ROS2 Developer", email: "pavithra.23cs@siet.ac.in" },
    ],
    guide: {
      id: "advisor-uuid-demo-001",
      full_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
      email: "senthilkumar.cse@siet.ac.in",
      designation: "Associate Professor",
      department: "CSE",
    },
  },
  {
    id: "team-uuid-epsilon-005",
    team_id: "team-uuid-epsilon-005",
    name: "Team Epsilon (CSE-B)",
    project_title: "Cloud-Native Microservices Security & Automated Vulnerability Remediation",
    batch: "Batch 2023-27",
    section: "Sec B",
    department: "Computer Science & Engineering",
    current_phase: "Phase I Review",
    submission_status: "NOT_SUBMITTED",
    evaluation_status: "NOT_SUBMITTED",
    marks_awarded: undefined,
    leader_name: "Arun Prakash",
    leader_roll: "23CS061",
    members: [
      { id: "s17", full_name: "Arun Prakash", roll_number: "23CS061", role: "DevSecOps Engineer", email: "arun.23cs@siet.ac.in" },
      { id: "s18", full_name: "Swathi M", roll_number: "23CS062", role: "Kubernetes Operator Lead", email: "swathi.23cs@siet.ac.in" },
      { id: "s19", full_name: "Naveen Raj", roll_number: "23CS063", role: "eBPF Kernel Monitoring", email: "naveen.23cs@siet.ac.in" },
      { id: "s20", full_name: "Bhavana V", roll_number: "23CS064", role: "Security Compliance QA", email: "bhavana.23cs@siet.ac.in" },
    ],
    guide: {
      id: "advisor-uuid-demo-001",
      full_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
      email: "senthilkumar.cse@siet.ac.in",
      designation: "Associate Professor",
      department: "CSE",
    },
  },
];

export const mockAdvisorDashboard: import("@/types").AdvisorDashboardResponse = {
  total_teams: 5,
  total_students: 20,
  submitted_count: 4,
  evaluated_count: 2,
  pending_submissions: 1,
  pending_evaluations: 2,
  recent_submissions: [
    {
      team_id: "team-uuid-alpha-001",
      team_name: "Team Alpha (CSE-A)",
      project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
      submitted_at: "04 Sep 2026, 09:30 PM",
      status: "SUBMITTED",
      guide: {
        id: "advisor-uuid-demo-001",
        full_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
        email: "senthilkumar.cse@siet.ac.in",
        designation: "Associate Professor",
        department: "CSE",
      },
    },
    {
      team_id: "team-uuid-gamma-003",
      team_name: "Team Gamma (CSE-A)",
      project_title: "Automated Diabetic Retinopathy Screening via Multi-Modal Vision Transformer",
      submitted_at: "05 Sep 2026, 08:20 AM",
      status: "SUBMITTED",
      guide: {
        id: "advisor-uuid-demo-001",
        full_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
        email: "senthilkumar.cse@siet.ac.in",
        designation: "Associate Professor",
        department: "CSE",
      },
    },
    {
      team_id: "team-uuid-delta-004",
      team_name: "Team Delta (CSE-C)",
      project_title: "Autonomous Drone Swarm Navigation in GPS-Denied Environments",
      submitted_at: "05 Sep 2026, 10:45 AM",
      status: "SUBMITTED",
      guide: {
        id: "advisor-uuid-demo-001",
        full_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
        email: "senthilkumar.cse@siet.ac.in",
        designation: "Associate Professor",
        department: "CSE",
      },
    },
    {
      team_id: "team-uuid-beta-002",
      team_name: "Team Beta (CSE-B)",
      project_title: "Blockchain-Based Decentralized Credential Verification System",
      submitted_at: "03 Sep 2026, 05:15 PM",
      status: "SUBMITTED",
      guide: {
        id: "advisor-uuid-demo-001",
        full_name: "Dr. K. Senthil Kumar, M.E., Ph.D.",
        email: "senthilkumar.cse@siet.ac.in",
        designation: "Associate Professor",
        department: "CSE",
      },
    },
  ],
  recent_activities: [
    { id: "act-1", title: "Team Alpha uploaded final presentation slides and code commit", timestamp: "2 hours ago" },
    { id: "act-2", title: "Evaluated Team Beta: 88/100 (Approved)", timestamp: "4 hours ago" },
    { id: "act-3", title: "Team Gamma submitted Stage 2 milestone dossier", timestamp: "Yesterday at 6:45 PM" },
    { id: "act-4", title: "Evaluated Team Alpha: 92/100 (Outstanding)", timestamp: "2 days ago" },
    { id: "act-5", title: "Department PRC Committee convened Viva Session #2", timestamp: "3 days ago" },
  ],
};

export const mockAdvisorStudents: import("@/types").AdvisorStudent[] = [
  {
    id: "s1",
    roll_number: "23CS001",
    full_name: "Rahul Sharma",
    email: "rahul.23cs@siet.ac.in",
    team_name: "Team Alpha (CSE-A)",
    team_id: "team-uuid-alpha-001",
    technical_role: "AI Engineer & Team Leader",
    cgpa: 8.85,
    attendance_percentage: 94,
    evaluation_status: "EVALUATED",
    total_marks: 92,
    guide: mockAdvisorTeams[0].guide,
    evaluation_records: [
      {
        stage_number: 1,
        stage_title: "Stage 1 — Abstract & Scope Review",
        date: "Saturday, 15 Aug 2026",
        evaluator: "Department Project Review Committee",
        marks: 85,
        max_marks: 100,
        grade: "A",
        remarks: "Comprehensive problem definition and IEEE format adoption.",
        criteria_breakdown: { "Problem Scope": { score: 17, max: 20 }, "Methodology": { score: 17, max: 20 }, "Presentation": { score: 17, max: 20 }, "Viva": { score: 17, max: 20 }, "Feasibility": { score: 17, max: 20 } },
      },
      {
        stage_number: 2,
        stage_title: "Stage 2 — Progress & Model Benchmark Review",
        date: "Saturday, 22 Aug 2026",
        evaluator: "Department Project Review Committee",
        marks: 89,
        max_marks: 100,
        grade: "A+",
        remarks: "High FPS edge inference validated on Jetson hardware.",
        criteria_breakdown: { "Dataset": { score: 18, max: 20 }, "Augmentation": { score: 18, max: 20 }, "Code Quality": { score: 18, max: 20 }, "Latency": { score: 18, max: 20 }, "Defense": { score: 17, max: 20 } },
      },
      {
        stage_number: 3,
        stage_title: "Stage 3 — Final Viva Voce Examination",
        date: "Saturday, 29 Aug 2026",
        evaluator: "Dr. K. Senthil Kumar (PRC Guide)",
        marks: 92,
        max_marks: 100,
        grade: "O",
        remarks: "Outstanding technical mastery, flawless edge inference demo, robust error handling.",
        criteria_breakdown: { "Execution": { score: 19, max: 20 }, "Depth": { score: 18.5, max: 20 }, "Presentation": { score: 18, max: 20 }, "Docs": { score: 18.5, max: 20 }, "Contribution": { score: 18, max: 20 } },
      },
    ],
  },
  {
    id: "s2",
    roll_number: "23CS002",
    full_name: "Priya Sundaram",
    email: "priya.23cs@siet.ac.in",
    team_name: "Team Alpha (CSE-A)",
    team_id: "team-uuid-alpha-001",
    technical_role: "Computer Vision Specialist",
    cgpa: 8.72,
    attendance_percentage: 92,
    evaluation_status: "EVALUATED",
    total_marks: 92,
    guide: mockAdvisorTeams[0].guide,
  },
  {
    id: "s3",
    roll_number: "23CS003",
    full_name: "Karthik Raja",
    email: "karthik.23cs@siet.ac.in",
    team_name: "Team Alpha (CSE-A)",
    team_id: "team-uuid-alpha-001",
    technical_role: "Edge Computing & IoT Engineer",
    cgpa: 8.45,
    attendance_percentage: 91,
    evaluation_status: "EVALUATED",
    total_marks: 92,
    guide: mockAdvisorTeams[0].guide,
  },
  {
    id: "s4",
    roll_number: "23CS004",
    full_name: "Ananya Krishnan",
    email: "ananya.23cs@siet.ac.in",
    team_name: "Team Alpha (CSE-A)",
    team_id: "team-uuid-alpha-001",
    technical_role: "Full-Stack ERP Integrator",
    cgpa: 8.91,
    attendance_percentage: 96,
    evaluation_status: "EVALUATED",
    total_marks: 92,
    guide: mockAdvisorTeams[0].guide,
  },
  {
    id: "s5",
    roll_number: "23CS045",
    full_name: "Vigneshwaran K",
    email: "vignesh.23cs@siet.ac.in",
    team_name: "Team Beta (CSE-B)",
    team_id: "team-uuid-beta-002",
    technical_role: "Smart Contract Architect",
    cgpa: 8.65,
    attendance_percentage: 93,
    evaluation_status: "EVALUATED",
    total_marks: 88,
    guide: mockAdvisorTeams[1].guide,
  },
  {
    id: "s6",
    roll_number: "23CS046",
    full_name: "Sneha R",
    email: "sneha.23cs@siet.ac.in",
    team_name: "Team Beta (CSE-B)",
    team_id: "team-uuid-beta-002",
    technical_role: "Frontend Web3 Developer",
    cgpa: 8.58,
    attendance_percentage: 95,
    evaluation_status: "EVALUATED",
    total_marks: 88,
    guide: mockAdvisorTeams[1].guide,
  },
  {
    id: "s7",
    roll_number: "23CS047",
    full_name: "Deepak Kumar",
    email: "deepak.23cs@siet.ac.in",
    team_name: "Team Beta (CSE-B)",
    team_id: "team-uuid-beta-002",
    technical_role: "Zero-Knowledge Proof Engineer",
    cgpa: 8.35,
    attendance_percentage: 89,
    evaluation_status: "EVALUATED",
    total_marks: 88,
    guide: mockAdvisorTeams[1].guide,
  },
  {
    id: "s8",
    roll_number: "23CS048",
    full_name: "Lavanya M",
    email: "lavanya.23cs@siet.ac.in",
    team_name: "Team Beta (CSE-B)",
    team_id: "team-uuid-beta-002",
    technical_role: "Technical Documentation Lead",
    cgpa: 8.78,
    attendance_percentage: 97,
    evaluation_status: "EVALUATED",
    total_marks: 88,
    guide: mockAdvisorTeams[1].guide,
  },
  {
    id: "s9",
    roll_number: "23CS012",
    full_name: "Gowtham S",
    email: "gowtham.23cs@siet.ac.in",
    team_name: "Team Gamma (CSE-A)",
    team_id: "team-uuid-gamma-003",
    technical_role: "Medical AI Lead",
    cgpa: 8.52,
    attendance_percentage: 90,
    evaluation_status: "PENDING",
    guide: mockAdvisorTeams[2].guide,
  },
  {
    id: "s10",
    roll_number: "23CS013",
    full_name: "Keerthana V",
    email: "keerthana.23cs@siet.ac.in",
    team_name: "Team Gamma (CSE-A)",
    team_id: "team-uuid-gamma-003",
    technical_role: "Data Preprocessing & Augmentation",
    cgpa: 8.68,
    attendance_percentage: 93,
    evaluation_status: "PENDING",
    guide: mockAdvisorTeams[2].guide,
  },
  {
    id: "s11",
    roll_number: "23CS014",
    full_name: "Manoj P",
    email: "manoj.23cs@siet.ac.in",
    team_name: "Team Gamma (CSE-A)",
    team_id: "team-uuid-gamma-003",
    technical_role: "Backend Ingest API",
    cgpa: 8.24,
    attendance_percentage: 88,
    evaluation_status: "PENDING",
    guide: mockAdvisorTeams[2].guide,
  },
  {
    id: "s12",
    roll_number: "23CS015",
    full_name: "Divya N",
    email: "divya.23cs@siet.ac.in",
    team_name: "Team Gamma (CSE-A)",
    team_id: "team-uuid-gamma-003",
    technical_role: "UI/UX Clinical Dashboard",
    cgpa: 8.80,
    attendance_percentage: 96,
    evaluation_status: "PENDING",
    guide: mockAdvisorTeams[2].guide,
  },
  {
    id: "s13",
    roll_number: "23CS089",
    full_name: "Siddharth B",
    email: "siddharth.23cs@siet.ac.in",
    team_name: "Team Delta (CSE-C)",
    team_id: "team-uuid-delta-004",
    technical_role: "SLAM & Odometry Specialist",
    cgpa: 8.60,
    attendance_percentage: 92,
    evaluation_status: "PENDING",
    guide: mockAdvisorTeams[3].guide,
  },
  {
    id: "s14",
    roll_number: "23CS090",
    full_name: "Meera T",
    email: "meera.23cs@siet.ac.in",
    team_name: "Team Delta (CSE-C)",
    team_id: "team-uuid-delta-004",
    technical_role: "PX4 Firmware & Hardware",
    cgpa: 8.75,
    attendance_percentage: 94,
    evaluation_status: "PENDING",
    guide: mockAdvisorTeams[3].guide,
  },
  {
    id: "s15",
    roll_number: "23CS091",
    full_name: "Ashwin K",
    email: "ashwin.23cs@siet.ac.in",
    team_name: "Team Delta (CSE-C)",
    team_id: "team-uuid-delta-004",
    technical_role: "Mesh Communications Lead",
    cgpa: 8.31,
    attendance_percentage: 89,
    evaluation_status: "PENDING",
    guide: mockAdvisorTeams[3].guide,
  },
  {
    id: "s16",
    roll_number: "23CS092",
    full_name: "Pavithra S",
    email: "pavithra.23cs@siet.ac.in",
    team_name: "Team Delta (CSE-C)",
    team_id: "team-uuid-delta-004",
    technical_role: "Simulation & ROS2 Developer",
    cgpa: 8.94,
    attendance_percentage: 98,
    evaluation_status: "PENDING",
    guide: mockAdvisorTeams[3].guide,
  },
  {
    id: "s17",
    roll_number: "23CS061",
    full_name: "Arun Prakash",
    email: "arun.23cs@siet.ac.in",
    team_name: "Team Epsilon (CSE-B)",
    team_id: "team-uuid-epsilon-005",
    technical_role: "DevSecOps Engineer",
    cgpa: 8.42,
    attendance_percentage: 91,
    evaluation_status: "PENDING",
    guide: mockAdvisorTeams[4].guide,
  },
  {
    id: "s18",
    roll_number: "23CS062",
    full_name: "Swathi M",
    email: "swathi.23cs@siet.ac.in",
    team_name: "Team Epsilon (CSE-B)",
    team_id: "team-uuid-epsilon-005",
    technical_role: "Kubernetes Operator Lead",
    cgpa: 8.88,
    attendance_percentage: 95,
    evaluation_status: "PENDING",
    guide: mockAdvisorTeams[4].guide,
  },
  {
    id: "s19",
    roll_number: "23CS063",
    full_name: "Naveen Raj",
    email: "naveen.23cs@siet.ac.in",
    team_name: "Team Epsilon (CSE-B)",
    team_id: "team-uuid-epsilon-005",
    technical_role: "eBPF Kernel Monitoring",
    cgpa: 8.19,
    attendance_percentage: 87,
    evaluation_status: "PENDING",
    guide: mockAdvisorTeams[4].guide,
  },
  {
    id: "s20",
    roll_number: "23CS064",
    full_name: "Bhavana V",
    email: "bhavana.23cs@siet.ac.in",
    team_name: "Team Epsilon (CSE-B)",
    team_id: "team-uuid-epsilon-005",
    technical_role: "Security Compliance QA",
    cgpa: 8.67,
    attendance_percentage: 93,
    evaluation_status: "PENDING",
    guide: mockAdvisorTeams[4].guide,
  },
];

export const mockEvaluationSessions: import("@/types").AdvisorEvaluationSession[] = [
  {
    id: "session-2026-08-29",
    title: "Official PRC Examination Session",
    date: "Saturday, August 29, 2026",
    time: "3:30 PM",
    teams_count: 4,
    teams: [
      {
        id: "team-uuid-alpha-001",
        team_id: "team-uuid-alpha-001",
        name: "Team Alpha",
        project_title: "AI-Powered Smart Attendance & Campus Surveillance System",
        batch: "2023 - 2027",
        section: "CSE-A",
        department: "CSE",
        current_phase: "Review 3 - Final Phase",
        submission_date: "26 Aug 2026",
        submission_status: "APPROVED",
        evaluation_status: "EVALUATED",
        marks_awarded: 88,
        evaluation_score: 88,
        grade: "A",
        evaluated_by: "Dr. Savitha Devi, M.E., Ph.D. (Faculty Advisor / Mam)",
        evaluated_at: "Saturday, August 29, 2026 at 3:30 PM",
        evaluation_remarks:
          "Exceptional architecture, robust code repository, and thorough literature review. Meets all autonomous college guidelines.",
        submission_detail: {
          id: "sub-alpha-001",
          week_number: 12,
          week_title: "Review 3: Final Project Implementation & Oral Defense",
          is_current_week: false,
          submission_date: "26 Aug 2026",
          submission_time: "04:30 PM",
          deadline: "26 Aug 2026, 05:00 PM",
          is_late: false,
          status: "APPROVED" as any,
          submission_type: "Comprehensive Project Report & Source Code",
          guide_name: "Dr. Subramanian",
          progress_contribution: 100,
          is_locked: true,
          is_evaluated: true,
          marks_awarded: 88,
          max_marks: 100,
          grade: "A",
          evaluated_by: "Dr. Savitha Devi, M.E., Ph.D. (Faculty Advisor / Mam)",
          evaluated_at: "Saturday, August 29, 2026 at 3:30 PM",
          github_url: "https://github.com/siet-coe/team-alpha-surveillance",
          live_demo_url: "https://attendance-ai.siet.ac.in",
          problems_faced: "RTSP packet jitter under high network contention addressed via edge ring buffer.",
          next_week_plan: "Autonomous campus pilot deployment across 12 smart classrooms.",
          files: [
            {
              id: "f-alpha-1",
              name: "TeamAlpha_Comprehensive_Final_Report_v3.pdf",
              file_size: "4.8 MB",
              file_type: "application/pdf",
              url: "#",
              uploaded_at: "26 Aug 2026, 04:28 PM",
            } as any,
          ],
          attempts: [],
          timeline: [],
        },
        guide: {
          name: "Dr. Subramanian",
          designation: "Professor",
          department: "CSE",
          email: "subramanian.cse@siet.ac.in",
        },
        members: [
          {
            id: "m1",
            full_name: "Rahul Sharma",
            roll_number: "23CS001",
            role: "Core Contributor",
            email: "rahul.23cs@siet.ac.in",
          },
          {
            id: "m2",
            full_name: "Priya Dharshini",
            roll_number: "23CS014",
            role: "Core Contributor",
            email: "priya.23cs@siet.ac.in",
          },
          {
            id: "m3",
            full_name: "Karthik Raja",
            roll_number: "23CS028",
            role: "Core Contributor",
            email: "karthik.23cs@siet.ac.in",
          },
          {
            id: "m4",
            full_name: "Ananya Iyer",
            roll_number: "23CS042",
            role: "Core Contributor",
            email: "ananya.23cs@siet.ac.in",
          },
        ],
        evaluation: {
          criteria_scores: {
            project_execution: 19,
            technical_depth: 18.5,
            presentation_viva: 18,
            documentation: 14.5,
            contribution: 18,
          },
          total_score: 88,
          grade: "A",
          verdict: "APPROVED",
          remarks:
            "Exceptional architecture, robust code repository, and thorough literature review. Meets all autonomous college guidelines.",
          strengths:
            "Comprehensive architecture, clean modular code structure, and strong literature survey.",
          areas_for_improvement:
            "Expand automated test coverage and include benchmark latency graphs in the final appendix.",
          evaluated_by: "Dr. Savitha Devi, M.E., Ph.D. (Faculty Advisor / Mam)",
          evaluated_at: "Saturday, August 29, 2026 at 3:30 PM",
          status: "EVALUATED",
        },
      },
      {
        id: "team-uuid-beta-002",
        team_id: "team-uuid-beta-002",
        name: "Team Beta",
        project_title: "Autonomous Drone Delivery for Hospital Supplies",
        batch: "2023 - 2027",
        section: "CSE-C",
        department: "CSE",
        current_phase: "Review 3 - Final Phase",
        submission_date: "26 Aug 2026",
        submission_status: "APPROVED",
        evaluation_status: "EVALUATED",
        marks_awarded: 95,
        evaluation_score: 95,
        grade: "A+",
        evaluated_by: "Dr. Savitha Devi, M.E., Ph.D. (Faculty Advisor / Mam)",
        evaluated_at: "Saturday, August 29, 2026 at 3:30 PM",
        evaluation_remarks:
          "Outstanding hardware integration, autonomous flight stability, and precision payload release demonstrated.",
        submission_detail: {
          id: "sub-beta-002",
          week_number: 12,
          week_title: "Review 3: Drone Flight Telemetry & Payload Mechanism",
          is_current_week: false,
          submission_date: "26 Aug 2026",
          submission_time: "02:15 PM",
          deadline: "26 Aug 2026, 05:00 PM",
          is_late: false,
          status: "APPROVED" as any,
          submission_type: "Hardware Prototype Report & Flight Logs",
          guide_name: "Dr. Arun Kumar",
          progress_contribution: 100,
          is_locked: true,
          is_evaluated: true,
          marks_awarded: 95,
          max_marks: 100,
          grade: "A+",
          evaluated_by: "Dr. Savitha Devi, M.E., Ph.D. (Faculty Advisor / Mam)",
          evaluated_at: "Saturday, August 29, 2026 at 3:30 PM",
          github_url: "https://github.com/siet-coe/autonomous-drone-delivery",
          live_demo_url: "https://drone-telemetry.siet.ac.in",
          problems_faced: "Motor PID tuning under 20km/h crosswinds optimized.",
          next_week_plan: "Conduct inter-hospital corridor autonomous flight trials.",
          files: [
            {
              id: "f-beta-1",
              name: "TeamBeta_Drone_Autonomous_Flight_Report.pdf",
              file_size: "6.2 MB",
              file_type: "application/pdf",
              url: "#",
              uploaded_at: "26 Aug 2026, 02:10 PM",
            } as any,
          ],
          attempts: [],
          timeline: [],
        },
        guide: {
          name: "Dr. Arun Kumar",
          designation: "Assistant Professor",
          department: "CSE",
          email: "arunkumar.cse@siet.ac.in",
        },
        members: [
          {
            id: "m5",
            full_name: "Siddharth B",
            roll_number: "23CS089",
            role: "Core Contributor",
            email: "siddharth.23cs@siet.ac.in",
          },
          {
            id: "m6",
            full_name: "Meera T",
            roll_number: "23CS090",
            role: "Core Contributor",
            email: "meera.23cs@siet.ac.in",
          },
          {
            id: "m7",
            full_name: "Ashwin K",
            roll_number: "23CS091",
            role: "Core Contributor",
            email: "ashwin.23cs@siet.ac.in",
          },
          {
            id: "m8",
            full_name: "Pavithra S",
            roll_number: "23CS092",
            role: "Core Contributor",
            email: "pavithra.23cs@siet.ac.in",
          },
        ],
        evaluation: {
          criteria_scores: {
            project_execution: 19.5,
            technical_depth: 19,
            presentation_viva: 19,
            documentation: 18.5,
            contribution: 19,
          },
          total_score: 95,
          grade: "A+",
          verdict: "APPROVED",
          remarks:
            "Outstanding hardware integration, autonomous flight stability, and precision payload release demonstrated.",
          strengths:
            "Excellent hardware-in-the-loop simulation and fault-tolerant fail-safe protocols.",
          areas_for_improvement:
            "Conduct thermal dissipation testing during prolonged outdoor hovering tests.",
          evaluated_by: "Dr. Arun Kumar",
          evaluated_at: "Saturday, August 29, 2026 at 3:30 PM",
          status: "EVALUATED",
        },
      },
      {
        id: "team-uuid-gamma-003",
        team_id: "team-uuid-gamma-003",
        name: "Team Gamma",
        project_title: "IoT Sensor Fusion for Precision Agriculture & Irrigation",
        batch: "2023 - 2027",
        section: "CSE-A",
        department: "CSE",
        current_phase: "Review 3 - Final Phase",
        submission_date: "26 Aug 2026",
        submission_status: "APPROVED",
        evaluation_status: "EVALUATED",
        marks_awarded: 90,
        evaluation_score: 90,
        grade: "A+",
        evaluated_by: "Dr. Meena Devi",
        evaluated_at: "Saturday, August 29, 2026 at 3:30 PM",
        evaluation_remarks:
          "Great telemetry throughput, robust LoRaWAN mesh communication, and intuitive farmer dashboard.",
        guide: {
          name: "Dr. Meena Devi",
          designation: "Professor",
          department: "CSE",
          email: "meenadevi.cse@siet.ac.in",
        },
        members: [
          {
            id: "m9",
            full_name: "Sanjay K",
            roll_number: "23CS021",
            role: "Core Contributor",
            email: "sanjay.23cs@siet.ac.in",
          },
          {
            id: "m10",
            full_name: "Deepa R",
            roll_number: "23CS022",
            role: "Core Contributor",
            email: "deepa.23cs@siet.ac.in",
          },
          {
            id: "m11",
            full_name: "Vignesh M",
            roll_number: "23CS023",
            role: "Core Contributor",
            email: "vignesh.23cs@siet.ac.in",
          },
          {
            id: "m12",
            full_name: "Divya S",
            roll_number: "23CS024",
            role: "Core Contributor",
            email: "divya.23cs@siet.ac.in",
          },
        ],
        evaluation: {
          criteria_scores: {
            project_execution: 18,
            technical_depth: 18.5,
            presentation_viva: 18,
            documentation: 17.5,
            contribution: 18,
          },
          total_score: 90,
          grade: "A+",
          verdict: "APPROVED",
          remarks:
            "Great telemetry throughput, robust LoRaWAN mesh communication, and intuitive farmer dashboard.",
          strengths:
            "Low power consumption profiles and solar harvesting circuit design.",
          areas_for_improvement:
            "Calibrate soil moisture capacitance sensors against clay-rich soil variants.",
          evaluated_by: "Dr. Meena Devi",
          evaluated_at: "Saturday, August 29, 2026 at 3:30 PM",
          status: "EVALUATED",
        },
      },
      {
        id: "team-uuid-delta-004",
        team_id: "team-uuid-delta-004",
        name: "Team Delta",
        project_title: "Decentralized Credential Verification using Polygon",
        batch: "2023 - 2027",
        section: "CSE-B",
        department: "CSE",
        current_phase: "Review 3 - Final Phase",
        submission_date: "26 Aug 2026",
        submission_status: "APPROVED",
        evaluation_status: "EVALUATED",
        marks_awarded: 88,
        evaluation_score: 88,
        grade: "A",
        evaluated_by: "Dr. K. Rajesh",
        evaluated_at: "Saturday, August 29, 2026 at 3:30 PM",
        evaluation_remarks:
          "Clean ERC-721 smart contract architecture and gas-optimized batch issuance verification.",
        guide: {
          name: "Dr. K. Rajesh",
          designation: "Associate Professor",
          department: "CSE",
          email: "rajesh.cse@siet.ac.in",
        },
        members: [
          {
            id: "m13",
            full_name: "Arun Prakash",
            roll_number: "23CS061",
            role: "Core Contributor",
            email: "arun.23cs@siet.ac.in",
          },
          {
            id: "m14",
            full_name: "Swathi M",
            roll_number: "23CS062",
            role: "Core Contributor",
            email: "swathi.23cs@siet.ac.in",
          },
          {
            id: "m15",
            full_name: "Naveen Raj",
            roll_number: "23CS063",
            role: "Core Contributor",
            email: "naveen.23cs@siet.ac.in",
          },
          {
            id: "m16",
            full_name: "Bhavana V",
            roll_number: "23CS064",
            role: "Core Contributor",
            email: "bhavana.23cs@siet.ac.in",
          },
        ],
        evaluation: {
          criteria_scores: {
            project_execution: 18,
            technical_depth: 17.5,
            presentation_viva: 18,
            documentation: 17,
            contribution: 17.5,
          },
          total_score: 88,
          grade: "A",
          verdict: "APPROVED",
          remarks:
            "Clean ERC-721 smart contract architecture and gas-optimized batch issuance verification.",
          strengths:
            "Zero-knowledge proof verification pipeline and intuitive QR credential verifier.",
          areas_for_improvement:
            "Optimize IPFS pin persistence and enhance mobile responsive wallet connect flow.",
          evaluated_by: "Dr. K. Rajesh",
          evaluated_at: "Saturday, August 29, 2026 at 3:30 PM",
          status: "EVALUATED",
        },
      },
    ],
  },
  {
    id: "session-2026-08-28",
    title: "Official PRC Examination Session",
    date: "Friday, August 28, 2026",
    time: "11:00 AM",
    teams_count: 3,
    teams: [
      {
        id: "team-uuid-epsilon-005",
        team_id: "team-uuid-epsilon-005",
        name: "Team Epsilon",
        project_title: "Real-Time Brain Tumor Segmentation from 3D MRI Scans",
        batch: "2023 - 2027",
        section: "CSE-A",
        department: "CSE",
        current_phase: "Review 3 - Final Phase",
        submission_date: "25 Aug 2026",
        submission_status: "APPROVED",
        evaluation_status: "EVALUATED",
        marks_awarded: 94,
        evaluation_score: 94,
        grade: "A+",
        evaluated_by: "Dr. K. Senthil Kumar",
        evaluated_at: "Friday, August 28, 2026 at 11:00 AM",
        evaluation_remarks:
          "High Dice score achieved on BraTS dataset with 3D UNet transformer ensemble.",
        guide: {
          name: "Dr. K. Senthil Kumar",
          designation: "Associate Professor",
          department: "CSE",
          email: "senthilkumar.cse@siet.ac.in",
        },
        members: [
          { id: "m17", full_name: "Kishore R", roll_number: "23CS101", role: "Core Contributor" },
          { id: "m18", full_name: "Sneha P", roll_number: "23CS102", role: "Core Contributor" },
          { id: "m19", full_name: "Manoj K", roll_number: "23CS103", role: "Core Contributor" },
          { id: "m20", full_name: "Lavanya T", roll_number: "23CS104", role: "Core Contributor" },
        ],
        evaluation: {
          criteria_scores: {
            project_execution: 19,
            technical_depth: 19.5,
            presentation_viva: 18.5,
            documentation: 18,
            contribution: 19,
          },
          total_score: 94,
          grade: "A+",
          verdict: "APPROVED",
          remarks: "High Dice score achieved on BraTS dataset with 3D UNet transformer ensemble.",
          strengths: "Clinical validation protocol and multi-modal image registration.",
          areas_for_improvement: "Test with varied scanner magnetic field strengths.",
        },
      },
      {
        id: "team-uuid-zeta-006",
        team_id: "team-uuid-zeta-006",
        name: "Team Zeta",
        project_title: "Autonomous EV Fleet Charging & Route Optimization",
        batch: "2023 - 2027",
        section: "CSE-B",
        department: "CSE",
        current_phase: "Review 3 - Final Phase",
        submission_date: "25 Aug 2026",
        submission_status: "APPROVED",
        evaluation_status: "EVALUATED",
        marks_awarded: 89,
        evaluation_score: 89,
        grade: "A",
        evaluated_by: "Dr. P. Mohanraj",
        evaluated_at: "Friday, August 28, 2026 at 11:00 AM",
        evaluation_remarks: "Effective reinforcement learning formulation for dynamic grid pricing.",
        guide: {
          name: "Dr. P. Mohanraj",
          designation: "Associate Professor",
          department: "CSE",
          email: "mohanraj.cse@siet.ac.in",
        },
        members: [
          { id: "m21", full_name: "Gokul N", roll_number: "23CS105", role: "Core Contributor" },
          { id: "m22", full_name: "Sandhya V", roll_number: "23CS106", role: "Core Contributor" },
          { id: "m23", full_name: "Harish S", roll_number: "23CS107", role: "Core Contributor" },
          { id: "m24", full_name: "Keerthana M", roll_number: "23CS108", role: "Core Contributor" },
        ],
        evaluation: {
          criteria_scores: {
            project_execution: 18,
            technical_depth: 18,
            presentation_viva: 17.5,
            documentation: 17.5,
            contribution: 18,
          },
          total_score: 89,
          grade: "A",
          verdict: "APPROVED",
          remarks: "Effective reinforcement learning formulation for dynamic grid pricing.",
          strengths: "SUMO simulation pipeline and tariff curve prediction.",
          areas_for_improvement: "Incorporate battery degradation modeling.",
        },
      },
      {
        id: "team-uuid-eta-007",
        team_id: "team-uuid-eta-007",
        name: "Team Eta",
        project_title: "Secure Federated Learning for Multihospital Analytics",
        batch: "2023 - 2027",
        section: "CSE-C",
        department: "CSE",
        current_phase: "Review 3 - Final Phase",
        submission_date: "25 Aug 2026",
        submission_status: "APPROVED",
        evaluation_status: "EVALUATED",
        marks_awarded: 92,
        evaluation_score: 92,
        grade: "A+",
        evaluated_by: "Dr. R. Kavitha",
        evaluated_at: "Friday, August 28, 2026 at 11:00 AM",
        evaluation_remarks: "Robust differential privacy implementation with Homomorphic encryption.",
        guide: {
          name: "Dr. R. Kavitha",
          designation: "Professor",
          department: "CSE",
          email: "kavitha.cse@siet.ac.in",
        },
        members: [
          { id: "m25", full_name: "Dinesh K", roll_number: "23CS109", role: "Core Contributor" },
          { id: "m26", full_name: "Reshma S", roll_number: "23CS110", role: "Core Contributor" },
          { id: "m27", full_name: "Saravanan P", roll_number: "23CS111", role: "Core Contributor" },
          { id: "m28", full_name: "Nithya R", roll_number: "23CS112", role: "Core Contributor" },
        ],
        evaluation: {
          criteria_scores: {
            project_execution: 18.5,
            technical_depth: 19,
            presentation_viva: 18,
            documentation: 18,
            contribution: 18.5,
          },
          total_score: 92,
          grade: "A+",
          verdict: "APPROVED",
          remarks: "Robust differential privacy implementation with Homomorphic encryption.",
          strengths: "PySyft and Flower integration with secure aggregator.",
          areas_for_improvement: "Benchmark network serialization overhead over WAN.",
        },
      },
    ],
  },
  {
    id: "session-2026-08-26",
    title: "Official PRC Examination Session",
    date: "Wednesday, August 26, 2026",
    time: "2:15 PM",
    teams_count: 5,
    teams: [
      {
        id: "team-uuid-theta-008",
        team_id: "team-uuid-theta-008",
        name: "Team Theta",
        project_title: "Smart Grid Fault Detection using Wavelet Analysis & Edge AI",
        batch: "2023 - 2027",
        section: "EEE-A",
        department: "EEE",
        current_phase: "Review 3 - Final Phase",
        submission_date: "23 Aug 2026",
        submission_status: "APPROVED",
        evaluation_status: "EVALUATED",
        marks_awarded: 91,
        evaluation_score: 91,
        grade: "A+",
        evaluated_by: "Dr. S. Karthikeyan",
        evaluated_at: "Wednesday, August 26, 2026 at 2:15 PM",
        evaluation_remarks: "Accurate transient fault classification within 15 milliseconds on FPGA.",
        guide: {
          name: "Dr. S. Karthikeyan",
          designation: "Professor",
          department: "EEE",
          email: "karthikeyan.eee@siet.ac.in",
        },
        members: [
          { id: "m29", full_name: "Vasanth J", roll_number: "23EE001", role: "Core Contributor" },
          { id: "m30", full_name: "Janani K", roll_number: "23EE002", role: "Core Contributor" },
          { id: "m31", full_name: "Prabhu R", roll_number: "23EE003", role: "Core Contributor" },
          { id: "m32", full_name: "Shalini S", roll_number: "23EE004", role: "Core Contributor" },
        ],
        evaluation: {
          criteria_scores: {
            project_execution: 18.5,
            technical_depth: 18.5,
            presentation_viva: 18,
            documentation: 18,
            contribution: 18,
          },
          total_score: 91,
          grade: "A+",
          verdict: "APPROVED",
          remarks: "Accurate transient fault classification within 15 milliseconds on FPGA.",
          strengths: "Real-time PMU telemetry ingestion and wavelet transform hardware implementation.",
          areas_for_improvement: "Test across non-linear load perturbations.",
        },
      },
      {
        id: "team-uuid-iota-009",
        team_id: "team-uuid-iota-009",
        name: "Team Iota",
        project_title: "AI Robotic Arm for Precision Electronic Assembly",
        batch: "2023 - 2027",
        section: "Mech-B",
        department: "Mech",
        current_phase: "Review 3 - Final Phase",
        submission_date: "23 Aug 2026",
        submission_status: "APPROVED",
        evaluation_status: "EVALUATED",
        marks_awarded: 87,
        evaluation_score: 87,
        grade: "A",
        evaluated_by: "Dr. V. Lakshmi",
        evaluated_at: "Wednesday, August 26, 2026 at 2:15 PM",
        evaluation_remarks: "Sub-millimeter pick-and-place accuracy achieved with RGB-D depth camera.",
        guide: {
          name: "Dr. V. Lakshmi",
          designation: "Assistant Professor",
          department: "Mech",
          email: "lakshmi.mech@siet.ac.in",
        },
        members: [
          { id: "m33", full_name: "Ajith Kumar", roll_number: "23ME005", role: "Core Contributor" },
          { id: "m34", full_name: "Preethi M", roll_number: "23ME006", role: "Core Contributor" },
          { id: "m35", full_name: "Gautham T", roll_number: "23ME007", role: "Core Contributor" },
          { id: "m36", full_name: "Sowmya N", roll_number: "23ME008", role: "Core Contributor" },
        ],
        evaluation: {
          criteria_scores: {
            project_execution: 17.5,
            technical_depth: 17.5,
            presentation_viva: 17,
            documentation: 17.5,
            contribution: 17.5,
          },
          total_score: 87,
          grade: "A",
          verdict: "APPROVED",
          remarks: "Sub-millimeter pick-and-place accuracy achieved with RGB-D depth camera.",
          strengths: "Custom 6-DoF inverse kinematics and gripper force feedback sensor.",
          areas_for_improvement: "Enhance trajectory smoothing during rapid payload changes.",
        },
      },
      {
        id: "team-uuid-kappa-010",
        team_id: "team-uuid-kappa-010",
        name: "Team Kappa",
        project_title: "NLP-Based Multi-Lingual Legal Case Summarization",
        batch: "2023 - 2027",
        section: "CSE-C",
        department: "CSE",
        current_phase: "Review 3 - Final Phase",
        submission_date: "23 Aug 2026",
        submission_status: "APPROVED",
        evaluation_status: "EVALUATED",
        marks_awarded: 90,
        evaluation_score: 90,
        grade: "A+",
        evaluated_by: "Dr. M. Suresh",
        evaluated_at: "Wednesday, August 26, 2026 at 2:15 PM",
        evaluation_remarks: "Accurate Indian penal code extraction and English/Tamil cross-lingual summary.",
        guide: {
          name: "Dr. M. Suresh",
          designation: "Associate Professor",
          department: "CSE",
          email: "suresh.cse@siet.ac.in",
        },
        members: [
          { id: "m37", full_name: "Akash V", roll_number: "23CS113", role: "Core Contributor" },
          { id: "m38", full_name: "Monisha D", roll_number: "23CS114", role: "Core Contributor" },
          { id: "m39", full_name: "Deepak G", roll_number: "23CS115", role: "Core Contributor" },
          { id: "m40", full_name: "Subhashree R", roll_number: "23CS116", role: "Core Contributor" },
        ],
        evaluation: {
          criteria_scores: {
            project_execution: 18,
            technical_depth: 18,
            presentation_viva: 18,
            documentation: 18,
            contribution: 18,
          },
          total_score: 90,
          grade: "A+",
          verdict: "APPROVED",
          remarks: "Accurate Indian penal code extraction and English/Tamil cross-lingual summary.",
          strengths: "LoRA fine-tuning on supreme court verdicts with high ROUGE-L metrics.",
          areas_for_improvement: "Include confidence calibration scores in output summaries.",
        },
      },
      {
        id: "team-uuid-lambda-011",
        team_id: "team-uuid-lambda-011",
        name: "Team Lambda",
        project_title: "Underwater Autonomous ROV for Marine Pipeline Inspection",
        batch: "2023 - 2027",
        section: "ECE-A",
        department: "ECE",
        current_phase: "Review 3 - Final Phase",
        submission_date: "23 Aug 2026",
        submission_status: "APPROVED",
        evaluation_status: "EVALUATED",
        marks_awarded: 89,
        evaluation_score: 89,
        grade: "A",
        evaluated_by: "Dr. N. Balakrishnan",
        evaluated_at: "Wednesday, August 26, 2026 at 2:15 PM",
        evaluation_remarks: "Ultrasonic acoustic positioning and computer vision defect detector tested in tank.",
        guide: {
          name: "Dr. N. Balakrishnan",
          designation: "Professor",
          department: "ECE",
          email: "balakrishnan.ece@siet.ac.in",
        },
        members: [
          { id: "m41", full_name: "Surya K", roll_number: "23EC009", role: "Core Contributor" },
          { id: "m42", full_name: "Madhumitha P", roll_number: "23EC010", role: "Core Contributor" },
          { id: "m43", full_name: "Ranjith S", roll_number: "23EC011", role: "Core Contributor" },
          { id: "m44", full_name: "Kavya B", roll_number: "23EC012", role: "Core Contributor" },
        ],
        evaluation: {
          criteria_scores: {
            project_execution: 18,
            technical_depth: 18,
            presentation_viva: 17.5,
            documentation: 17.5,
            contribution: 18,
          },
          total_score: 89,
          grade: "A",
          verdict: "APPROVED",
          remarks: "Ultrasonic acoustic positioning and computer vision defect detector tested in tank.",
          strengths: "Watertight hull telemetry sealing and live sonar visualization feed.",
          areas_for_improvement: "Improve thruster response under turbulent cross-currents.",
        },
      },
      {
        id: "team-uuid-mu-012",
        team_id: "team-uuid-mu-012",
        name: "Team Mu",
        project_title: "Quantum Key Distribution Simulation for Bank Networks",
        batch: "2023 - 2027",
        section: "CSE-B",
        department: "CSE",
        current_phase: "Review 3 - Final Phase",
        submission_date: "23 Aug 2026",
        submission_status: "APPROVED",
        evaluation_status: "EVALUATED",
        marks_awarded: 93,
        evaluation_score: 93,
        grade: "A+",
        evaluated_by: "Dr. A. Venkatesh",
        evaluated_at: "Wednesday, August 26, 2026 at 2:15 PM",
        evaluation_remarks: "BB84 protocol simulation with realistic fiber attenuation and decoy state method.",
        guide: {
          name: "Dr. A. Venkatesh",
          designation: "Associate Professor",
          department: "CSE",
          email: "venkatesh.cse@siet.ac.in",
        },
        members: [
          { id: "m45", full_name: "Naveen Kumar", roll_number: "23CS117", role: "Core Contributor" },
          { id: "m46", full_name: "Abinaya V", roll_number: "23CS118", role: "Core Contributor" },
          { id: "m47", full_name: "Saran Raj", roll_number: "23CS119", role: "Core Contributor" },
          { id: "m48", full_name: "Divya Bharathi", roll_number: "23CS120", role: "Core Contributor" },
        ],
        evaluation: {
          criteria_scores: {
            project_execution: 19,
            technical_depth: 19,
            presentation_viva: 18.5,
            documentation: 18,
            contribution: 18.5,
          },
          total_score: 93,
          grade: "A+",
          verdict: "APPROVED",
          remarks: "BB84 protocol simulation with realistic fiber attenuation and decoy state method.",
          strengths: "Comprehensive QBER threshold analysis and photon number splitting eavesdropping simulation.",
          areas_for_improvement: "Validate quantum bit error rate under simulated fiber temperature fluctuation.",
        },
      },
    ],
  },
];


